// Package storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package storage

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// Defines values for StorageSpecAccessMode.
const (
	ReadOnlyMany     StorageSpecAccessMode = "read_only_many"
	ReadWriteMany    StorageSpecAccessMode = "read_write_many"
	ReadWriteOnce    StorageSpecAccessMode = "read_write_once"
	ReadWriteOncePod StorageSpecAccessMode = "read_write_once_pod"
)

// Valid indicates whether the value is a known member of the StorageSpecAccessMode enum.
func (e StorageSpecAccessMode) Valid() bool {
	switch e {
	case ReadOnlyMany:
		return true
	case ReadWriteMany:
		return true
	case ReadWriteOnce:
		return true
	case ReadWriteOncePod:
		return true
	default:
		return false
	}
}

// Defines values for StorageSpecVolumeMode.
const (
	Block      StorageSpecVolumeMode = "block"
	Filesystem StorageSpecVolumeMode = "filesystem"
)

// Valid indicates whether the value is a known member of the StorageSpecVolumeMode enum.
func (e StorageSpecVolumeMode) Valid() bool {
	switch e {
	case Block:
		return true
	case Filesystem:
		return true
	default:
		return false
	}
}

// StorageSpec defines model for StorageSpec.
type StorageSpec struct {
	// AccessMode Attachment concurrency (Kubernetes PVC accessModes: RWO/ROX/RWX/RWOP).
	AccessMode StorageSpecAccessMode `json:"access_mode"`

	// Attached Whether the volume is currently attached to a consumer.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	Attached *bool `json:"attached,omitempty"`

	// Capacity Requested capacity, Kubernetes quantity form (e.g. 100Gi). SNIA Swordfish CapacityBytes maps here.
	Capacity string `json:"capacity"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// LayoutEntry The Storage.Layout entry name this volume realizes — the join key paired with the realizes_layout_entry edge. Instance edges carry no qualifier (the dependencies[] of a record is a closed shape, state-record.schema.json), so the entry binding lives HERE: set exactly when realizes_layout_entry is declared, matching an entry name in the referenced layout. Reconvergence joins on this value to populate the layout's realized_volumes map.
	LayoutEntry *string `json:"layout_entry,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// RetainOnRelease Reclaim policy: true = Retain (keep data after the consumer releases it), false = Delete.
	RetainOnRelease *bool `json:"retain_on_release,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// StorageClass Resource reference to a Storage.Class (common-elements §2.5, DCM ADR-025). Authored by handle; deferred resolution supported (claim-before-define).
	StorageClass *string `json:"storage_class,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// VolumeHandle Provider volume handle/id once Realized (CSI volumeHandle / Swordfish Volume Id).
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	VolumeHandle *string `json:"volume_handle,omitempty"`

	// VolumeMode Filesystem-mounted vs raw block device (Kubernetes PVC volumeMode).
	VolumeMode           *StorageSpecVolumeMode `json:"volume_mode,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StorageSpecAccessMode Attachment concurrency (Kubernetes PVC accessModes: RWO/ROX/RWX/RWOP).
type StorageSpecAccessMode string

// StorageSpecVolumeMode Filesystem-mounted vs raw block device (Kubernetes PVC volumeMode).
type StorageSpecVolumeMode string

// Getter for additional properties for StorageSpec. Returns the specified
// element and whether it was found
func (a StorageSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StorageSpec
func (a *StorageSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StorageSpec to handle AdditionalProperties
func (a *StorageSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_mode"]; found {
		err = json.Unmarshal(raw, &a.AccessMode)
		if err != nil {
			return fmt.Errorf("error reading 'access_mode': %w", err)
		}
		delete(object, "access_mode")
	}

	if raw, found := object["attached"]; found {
		err = json.Unmarshal(raw, &a.Attached)
		if err != nil {
			return fmt.Errorf("error reading 'attached': %w", err)
		}
		delete(object, "attached")
	}

	if raw, found := object["capacity"]; found {
		err = json.Unmarshal(raw, &a.Capacity)
		if err != nil {
			return fmt.Errorf("error reading 'capacity': %w", err)
		}
		delete(object, "capacity")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["layout_entry"]; found {
		err = json.Unmarshal(raw, &a.LayoutEntry)
		if err != nil {
			return fmt.Errorf("error reading 'layout_entry': %w", err)
		}
		delete(object, "layout_entry")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["retain_on_release"]; found {
		err = json.Unmarshal(raw, &a.RetainOnRelease)
		if err != nil {
			return fmt.Errorf("error reading 'retain_on_release': %w", err)
		}
		delete(object, "retain_on_release")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["storage_class"]; found {
		err = json.Unmarshal(raw, &a.StorageClass)
		if err != nil {
			return fmt.Errorf("error reading 'storage_class': %w", err)
		}
		delete(object, "storage_class")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["volume_handle"]; found {
		err = json.Unmarshal(raw, &a.VolumeHandle)
		if err != nil {
			return fmt.Errorf("error reading 'volume_handle': %w", err)
		}
		delete(object, "volume_handle")
	}

	if raw, found := object["volume_mode"]; found {
		err = json.Unmarshal(raw, &a.VolumeMode)
		if err != nil {
			return fmt.Errorf("error reading 'volume_mode': %w", err)
		}
		delete(object, "volume_mode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StorageSpec to handle AdditionalProperties
func (a StorageSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_mode"], err = json.Marshal(a.AccessMode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_mode': %w", err)
	}

	if a.Attached != nil {
		object["attached"], err = json.Marshal(a.Attached)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attached': %w", err)
		}
	}

	object["capacity"], err = json.Marshal(a.Capacity)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'capacity': %w", err)
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.LayoutEntry != nil {
		object["layout_entry"], err = json.Marshal(a.LayoutEntry)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'layout_entry': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	if a.RetainOnRelease != nil {
		object["retain_on_release"], err = json.Marshal(a.RetainOnRelease)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retain_on_release': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.StorageClass != nil {
		object["storage_class"], err = json.Marshal(a.StorageClass)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage_class': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	if a.VolumeHandle != nil {
		object["volume_handle"], err = json.Marshal(a.VolumeHandle)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume_handle': %w", err)
		}
	}

	if a.VolumeMode != nil {
		object["volume_mode"], err = json.Marshal(a.VolumeMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume_mode': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
