// Package cluster provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package cluster

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// ClusterSpec defines model for ClusterSpec.
type ClusterSpec struct {
	// ApiUrl Cluster API server URL once Realized.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	ApiUrl *string `json:"api_url,omitempty"`

	// ClusterId Provider-assigned cluster identifier.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	ClusterId *string `json:"cluster_id,omitempty"`

	// ConsoleUrl Web console URL.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	ConsoleUrl *string `json:"console_url,omitempty"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Kubeconfig Admin kubeconfig.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request. Sensitive: never logged, echoed, or diffed.
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Network Converted verbatim from the flat cluster spec.
	Network *Network `json:"network,omitempty"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// Release Platform release, e.g. 1.30 (a Kubernetes minor release) or a distribution's release stream.
	Release string `json:"release"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime           *time.Time             `json:"update_time,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Network Converted verbatim from the flat cluster spec.
type Network struct {
	PodCidr              *string                `json:"pod_cidr,omitempty"`
	ServiceCidr          *string                `json:"service_cidr,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for ClusterSpec. Returns the specified
// element and whether it was found
func (a ClusterSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClusterSpec
func (a *ClusterSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a *ClusterSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_url"]; found {
		err = json.Unmarshal(raw, &a.ApiUrl)
		if err != nil {
			return fmt.Errorf("error reading 'api_url': %w", err)
		}
		delete(object, "api_url")
	}

	if raw, found := object["cluster_id"]; found {
		err = json.Unmarshal(raw, &a.ClusterId)
		if err != nil {
			return fmt.Errorf("error reading 'cluster_id': %w", err)
		}
		delete(object, "cluster_id")
	}

	if raw, found := object["console_url"]; found {
		err = json.Unmarshal(raw, &a.ConsoleUrl)
		if err != nil {
			return fmt.Errorf("error reading 'console_url': %w", err)
		}
		delete(object, "console_url")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["kubeconfig"]; found {
		err = json.Unmarshal(raw, &a.Kubeconfig)
		if err != nil {
			return fmt.Errorf("error reading 'kubeconfig': %w", err)
		}
		delete(object, "kubeconfig")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["network"]; found {
		err = json.Unmarshal(raw, &a.Network)
		if err != nil {
			return fmt.Errorf("error reading 'network': %w", err)
		}
		delete(object, "network")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["release"]; found {
		err = json.Unmarshal(raw, &a.Release)
		if err != nil {
			return fmt.Errorf("error reading 'release': %w", err)
		}
		delete(object, "release")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a ClusterSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ApiUrl != nil {
		object["api_url"], err = json.Marshal(a.ApiUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'api_url': %w", err)
		}
	}

	if a.ClusterId != nil {
		object["cluster_id"], err = json.Marshal(a.ClusterId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cluster_id': %w", err)
		}
	}

	if a.ConsoleUrl != nil {
		object["console_url"], err = json.Marshal(a.ConsoleUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'console_url': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Kubeconfig != nil {
		object["kubeconfig"], err = json.Marshal(a.Kubeconfig)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kubeconfig': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Network != nil {
		object["network"], err = json.Marshal(a.Network)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'network': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["release"], err = json.Marshal(a.Release)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'release': %w", err)
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Network. Returns the specified
// element and whether it was found
func (a Network) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Network
func (a *Network) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a *Network) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pod_cidr"]; found {
		err = json.Unmarshal(raw, &a.PodCidr)
		if err != nil {
			return fmt.Errorf("error reading 'pod_cidr': %w", err)
		}
		delete(object, "pod_cidr")
	}

	if raw, found := object["service_cidr"]; found {
		err = json.Unmarshal(raw, &a.ServiceCidr)
		if err != nil {
			return fmt.Errorf("error reading 'service_cidr': %w", err)
		}
		delete(object, "service_cidr")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a Network) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PodCidr != nil {
		object["pod_cidr"], err = json.Marshal(a.PodCidr)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pod_cidr': %w", err)
		}
	}

	if a.ServiceCidr != nil {
		object["service_cidr"], err = json.Marshal(a.ServiceCidr)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'service_cidr': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
