// Code generated by cmd/udlm-servicetype-gen. DO NOT EDIT.

package servicetypes

// UDLMType is the UDLM class a service type was generated from.
type UDLMType struct {
	ResourceType string
	Version      string
}

// UDLMTypes maps a service type slug to the UDLM class and version it projects.
var UDLMTypes = map[string]UDLMType{
	"cluster":   {ResourceType: "KubernetesCluster", Version: "2.0.1"},
	"container": {ResourceType: "Container", Version: "1.0.2"},
	"database":  {ResourceType: "Data.Database", Version: "0.7.8"},
	"storage":   {ResourceType: "Volume", Version: "0.12.0"},
	"vm":        {ResourceType: "Machine.VM", Version: "2.0.1"},
}

// LookupUDLMType returns the UDLM class behind a service type slug.
func LookupUDLMType(slug string) (UDLMType, bool) {
	t, ok := UDLMTypes[slug]
	return t, ok
}

// UDLMOutput is one typed realized output a UDLM class declares (the E2 binding surface).
type UDLMOutput struct {
	// Type is the JSON Schema type of the output; empty when the registry leaves it untyped.
	Type string
	// Sensitive outputs are never logged, echoed, or diffed.
	Sensitive bool
}

// UDLMOutputs maps a service type slug to the outputs its UDLM class declares, by name.
var UDLMOutputs = map[string]map[string]UDLMOutput{
	"cluster": {
		"api_url":     {Type: "string", Sensitive: false},
		"cluster_id":  {Type: "string", Sensitive: false},
		"console_url": {Type: "string", Sensitive: false},
		"kubeconfig":  {Type: "string", Sensitive: true},
	},
	"container": {
		"endpoint":     {Type: "string", Sensitive: false},
		"internal_dns": {Type: "string", Sensitive: false},
	},
	"database": {
		"applied_version":   {Type: "string", Sensitive: false},
		"connection_string": {Type: "string", Sensitive: true},
		"host":              {Type: "string", Sensitive: false},
		"port":              {Type: "integer", Sensitive: false},
		"username":          {Type: "string", Sensitive: false},
	},
	"storage": {
		"attached":      {Type: "boolean", Sensitive: false},
		"volume_handle": {Type: "string", Sensitive: false},
	},
	"vm": {
		"hostname":           {Type: "string", Sensitive: false},
		"ip_addresses":       {Type: "array", Sensitive: false},
		"mac_addresses":      {Type: "array", Sensitive: false},
		"observed_run_state": {Type: "string", Sensitive: false},
		"primary_ip":         {Type: "string", Sensitive: false},
		"provider_handle":    {Type: "string", Sensitive: false},
		"target_segment":     {Type: "string", Sensitive: false},
	},
}

// LookupUDLMOutput returns one declared output of a service type's UDLM class.
func LookupUDLMOutput(slug, name string) (UDLMOutput, bool) {
	o, ok := UDLMOutputs[slug][name]
	return o, ok
}

// UDLMElements maps a service type slug to the top-level element names of its UDLM class —
// the only heads a dispatched path may have without a policy grant (DSP-002).
var UDLMElements = map[string][]string{
	"cluster":   {"network", "release"},
	"container": {"args", "command", "image", "network", "process", "resources", "runtime"},
	"database":  {"engine", "metadata", "resources", "version"},
	"storage":   {"access_mode", "capacity", "layout_entry", "retain_on_release", "storage_class", "volume_mode"},
	"vm":        {"boot_order", "cpu", "firmware", "guest_os", "instance_size", "layout_ref", "memory", "networks", "placement", "run_state", "storage", "storage_tier"},
}

// LookupUDLMElements returns the element names of a service type's UDLM class.
func LookupUDLMElements(slug string) ([]string, bool) {
	e, ok := UDLMElements[slug]
	return e, ok
}

// UDLMGroups maps a service type slug to the usage groups its UDLM class is filed under (ADR-082).
// Every offering of the type inherits them; an offering never declares its own.
var UDLMGroups = map[string][]string{
	"cluster":   {"compute"},
	"container": {"compute"},
	"database":  {},
	"storage":   {"storage"},
	"vm":        {"compute"},
}

// LookupUDLMGroups returns the usage groups of a service type's UDLM class.
func LookupUDLMGroups(slug string) ([]string, bool) {
	g, ok := UDLMGroups[slug]
	return g, ok
}

// UDLMUsageGroup is one term of the registry's usage-group vocabulary (registry/taxonomies/usage-group.yaml).
type UDLMUsageGroup struct {
	Term       string
	Definition string
}

// UDLMUsageGroups is the vocabulary, in the registry's order. The catalog's shelves.
var UDLMUsageGroups = []UDLMUsageGroup{
	{Term: "compute", Definition: "Things that run workloads — machines, containers, Kubernetes clusters, namespaces and node pools."},
	{Term: "storage", Definition: "Things that hold data — volumes, pools, storage clusters, file shares, storage classes, layouts."},
	{Term: "network", Definition: "Things that connect — addresses, pools, subnets, VLANs, virtual networks, switches, gateways, address services (DHCP, DNS), connection profiles."},
	{Term: "hardware", Definition: "Devices and components below the machine boundary — processors, GPUs, network interfaces, storage devices, BMCs, firmware profiles. Physical or virtual: `device_class` on the class says which."},
	{Term: "power", Definition: "Things that deliver or condition electrical power — UPS units, power feeds."},
	{Term: "facility", Definition: "Physical placement — locations, and the topologies (region, zone, rack, host) placement resolves against."},
	{Term: "data", Definition: "Managed data services — databases, and when they arrive, streams and queues."},
	{Term: "security", Definition: "Things that protect — credential references, directory services, certificates when they arrive."},
	{Term: "identity", Definition: "Who and what may act — identities, groupings, directory services. A directory server is filed here and under `services`; it is one class with two filings."},
	{Term: "observability", Definition: "Things that watch — log shippers, and when they arrive, scrape targets and collectors."},
	{Term: "services", Definition: "Installed or served software as an orderable thing — services, and templates that compose them into one offering."},
	{Term: "automation", Definition: "Things that run on behalf of the control plane — jobs, automation runs."},
}
