// Code generated by cmd/udlm-servicetype-gen. DO NOT EDIT.

package servicetypes

// UDLMType is the UDLM class a service type was generated from.
type UDLMType struct {
	ResourceType string
	Version      string
}

// UDLMTypes maps a service type slug to the UDLM class and version it projects.
var UDLMTypes = map[string]UDLMType{
	"cluster": {ResourceType: "KubernetesCluster", Version: "2.0.0"},
	"container": {ResourceType: "Container", Version: "1.0.2"},
	"database": {ResourceType: "Data.Database", Version: "0.7.7"},
	"storage": {ResourceType: "Storage.Volume", Version: "0.11.6"},
	"vm": {ResourceType: "Machine.VM", Version: "2.0.0"},
}

// LookupUDLMType returns the UDLM class behind a service type slug.
func LookupUDLMType(slug string) (UDLMType, bool) {
	t, ok := UDLMTypes[slug]
	return t, ok
}
