// Package provider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package provider

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvc9s20v8qGDydafJU/606jd90XNtJlbMdnS0303N8HohciUhIgAFA2UxO3/1mAZIiRcpWMznFM3fv",
	"RALYXSx2f/vDUl+oJ6NYChBG04MvNGaKRWBA2aexkgvugxr5Y2YCfOOD9hSPDZeCHtArwT8lQLgPwvAZ",
	"B0XkjJgASJwtpC0K9yyKQ6AHtD/Yg+HP+y/a8MvLabs/8PfabPjzfns42N/vD/svhr1ej7YoR8kx6mtR",
	"wSJcGRd20BZV8CnhCnx6YFQCLaq9ACKGxkXs/hTEHC3d32vRiIv8sd9CiQYUyv7nNWt/7rVf3jzLfrRv",
	"vvRa+/1l/v75rz/QFjVpjLq1UVzM6XK5RNU6lkKDdc4rqabc90HggyeFAWHwJ4vjkHsMXdT9oKUdLpyA",
	"HjSMh+g8DYr4EjQR0pCALYDEoCKuNZeCGEmY54HWxARcEwVaJsoD2qLaMJNoejDs7bWo4cb69tDNnRU2",
	"FfaPTy7ORpeXo7fnt8cn56OTY7os++wHBTN6QP+vu4qDrhvV3ROlpHI7r577auvLFr0SLDGBVPwznslX",
	"ueIPFnKfoBgMJLeAeApsXLFQE6aA5Oe+lWv6JddUxRbhU3jo6vzwavL7yflkdHQ4+Sb+qbhkWcizYeMW",
	"1VLp4tURefFL7wVBPSFnwhDAmSSPOdrCNIhBGe7iL/feuqTfk4iJtgLms2kIBO7jkAm3dx2Dx2fcQxda",
	"30nPS5QCYb23ytRJAORHzL0fyYxD6BPr5sz908SQO+aiNktMv54umMfaMJRch42LEVEwA6sYY9YZU1jn",
	"Nr7Btq4d1d0t0WQmVcQMPaCJ4u1CaZO9efDU/DmZjIkbJJ70K9YMe71CEhcG5qBQVBZ665IuA6kMCarn",
	"o5MoYiotIec0hKiy5ZFY2AQZiTgxTaa7Fw+7OQPplIu5VeScbFeWdQXGxPqg2/W9qJO97Xgyyr3OnSlt",
	"npmyrXuXZdy+ppla56ebYracfgDP4I7yylPf1askDIv6UiQ/URAr0CCMjfRasngKmIFbw6MGR014BNqw",
	"KCZ3AYhKAbORPuNKG6JgzrUBBx3Fvn1moG3F4g6Z/1aEaV6Zaufkcx2HLL11Ze2RxM0mE5ycJcmGwvq3",
	"ZAp/cGXIJagF94CMV7NqNoDwY8kdPjd4Nh8mVxen6A4FVX8cjkeIBg6A+TRsjh4d9yvRw2LeXfRZGAes",
	"311Ea4HTZGYALDTB7caktMN5Wj7EOtCf6TaHw/1tCE5+EA2u/stM59vylUc3GIFhPjOPlrV8S2f5/GVO",
	"xDa4x0ZodgYP+uVjMoUFV6bdH+w1HTpmrM3fhhM/5dqgktUcopM4lsqAX6ohmfp1XLvOEIBiqQ7B/khi",
	"TF6EH24gsio3ICtlSrEUn+NGHnyRoxAOl6Klsvk8OrcuXY8eqDuw2wUozR25Wqs3dpxk4/kJlV3kjmyc",
	"e1JXDM4TllaCcXGNIffTMzv2rykY9vxX++r/f2isqk7bbXOJmqANcrayCc+wwBo5m+FFpGJT1KTEneRX",
	"onvItCFOwtci+1p1s8lSQto1L9QOrlYAW/S+zSBuF9TW3szsEWhUsAqlL/nPW+4vUVAcJoqF5XBDfVzM",
	"k5Cp0uuSG51t+UAHKz+X3WLislSOMQnrHh6zORfoPhJmSVpWXi3EAu7NbczmcGvkR2gI2gm+tgmtwCgO",
	"i5yw4EqCK1GBAp2Ea/EK6Zv4H0ej/dGHk/RscNU7n/y5d/ruavj23cicTd58PEv7wfnx1eB08vf0/MOf",
	"9+fHJ3vnx4d3Z0dvXjZF1WoTB19WELENctaRY/kAxzkr4TLzfY6OYOG45DYXdFU/HRYzSQ7shE1lYtZL",
	"YdX/yGKkuLVEtub71yDnisUB94ibZwlvEw1wKAzVA0h0G5g27X6TN/NYftSJOZgesZh53KQPcfMje0Mw",
	"q6LAwm04gSMXaZOZn6VocMzhgvGQTXnITUpwCpGKoMs9EAbUJshfzWhPGzlxLSZqm99ca7xsCuHCYVYT",
	"7zXSsPDWi5OmRDMsJEfjK+JJBZowt8cqoxtsuOBYsRFEUqWbJLvRZrG0P/mt8SJj5YrG4HRSRRJNXZ8J",
	"Z1Xir/+QrdpIxeYbxWbDG6wdNFlbPz5b7rxEcZPa0uuOYApMgTpMHHFwT6/yIvPm3YSuZ/abdxNiwZHI",
	"qWFcIL9RMrLh7Ekx4/ME7+EosUyzbP6gOU7FymAk5a5LgZGSt2iYh0hea10cH53VOJwl/W1yYS9ALs8I",
	"Ez6JmGBziGwCzmqrdOe9mGA9t1cG9CTO1I0sMbtcZbJnobwjTBMfZnb33Fbt9wJtAxEw4TmlGOpSs7Dz",
	"HgM/5B4IbU84axsexswLgAw6yKYSFZYuKHd3dx1mhztSzbvZWt09HR2dnF+etAedXicwUVi6zdMmt9AW",
	"LejXijA5KitYzOkB3ev0OkPHoQIbEN1KYZmDaUpykyihCSsq6ur2WZClQgy54yYgMs4AcMZDAzZGS4x6",
	"5GccelwuzaVu73XtOmjFlLRM03V6bVu1nxJQ6apXW6E4DZx62VpXdMbueZREpdTOqjuJUT9mbbOqiN07",
	"KqH556pOH2YsCU2GCZFTkD9xkT3V0aJu3IqOxI7lOJRtMqfEah7a/81aH3nQ623RNt2uI1nhaQ2NycvE",
	"3ttnSbgqmRitwwdtyHpSP/01WzZ2R39jvu0mgjZOd3+TqMJP3WpHFRftPb6o0qYuQmJX27wScB+Dh7QY",
	"sjktmnX78vssK/WyMCENm1cIPr1BHip1I0Q4QCCMCLirgQISFHepIUwQuOfaIJGWAjrvRQXJuUb6EsUS",
	"fXLwXrTJaOau9MXHCbu8lWm6HBMQRqW40F2q/fIiOzeDJM0i6ApZGDU6brneY74+u3ZtWu/zme0omoqE",
	"aq1gPNTkGdbFkHvmeSZqNX+DQNT1qKgagB7Z/ZaK7oMI+jZH5OJQRscWSlb+rliwAVe4T3f3levGXWVB",
	"m9+kn35zYMq/o5U/4S13AIhNCVrU8SwKyTMF7fJ5PEfcGDh42p01WU6RZ5hsNXN2itT5hwfX7d8dVg97",
	"L3e3yaMs30k7a2SqMnqw0DaQkYMmGqxxg8HujLNfRh08wb0HcV6wn1o1K1Wjpo8Q9bK2bJV48KqNNfKX",
	"rtTZHm1D0YvkAgirl7vihpRlTFrD7mMrczN2N7llNaW79l+IBho3bOiM5ea5DflEFwQsTL9bOo+ObcM3",
	"5Hl+7iiph7vbauF4pC8zmQj/KWaNC8lSOD+cM63my+JrME0ZMU0JN5ok7hvN6LiWEK/B/AezYTc1/Elc",
	"aP6XV08sr1xGxI8kE3Ka+ifN+p1pPbNsXwvKJIFnn5WYCUiUaEMiZrygIqS0uJaIh3Ecpt82Ff9LGfyT",
	"KK+7Z8vfHQC+K2GvUnSse0xIE5R6l08Ro3Kg2ZYvlz4uWFQof1a4vsGsR5zKMcN1uyv/u7HIkEmu/VNg",
	"vbVdbu2v/pRR+0MuXd4s/x0AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
