// Package vm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package vm

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// Defines values for AffinityRule.
const (
	AffinityRuleAffinity     AffinityRule = "affinity"
	AffinityRuleAntiAffinity AffinityRule = "anti_affinity"
)

// Valid indicates whether the value is a known member of the AffinityRule enum.
func (e AffinityRule) Valid() bool {
	switch e {
	case AffinityRuleAffinity:
		return true
	case AffinityRuleAntiAffinity:
		return true
	default:
		return false
	}
}

// Defines values for NetworkIpMode.
const (
	Byo     NetworkIpMode = "byo"
	Dynamic NetworkIpMode = "dynamic"
	Static  NetworkIpMode = "static"
)

// Valid indicates whether the value is a known member of the NetworkIpMode enum.
func (e NetworkIpMode) Valid() bool {
	switch e {
	case Byo:
		return true
	case Dynamic:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for PowerDesiredState.
const (
	Running   PowerDesiredState = "running"
	Stopped   PowerDesiredState = "stopped"
	Suspended PowerDesiredState = "suspended"
)

// Valid indicates whether the value is a known member of the PowerDesiredState enum.
func (e PowerDesiredState) Valid() bool {
	switch e {
	case Running:
		return true
	case Stopped:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Affinity defines model for Affinity.
type Affinity struct {
	Rule AffinityRule `json:"rule"`

	// Target handle/uuid of an existing resource to co-locate with or avoid.
	Target               string                 `json:"target"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AffinityRule defines model for Affinity.Rule.
type AffinityRule string

// Disk defines model for Disk.
type Disk struct {
	Size                 string                 `json:"size"`
	StorageClass         *string                `json:"storage_class,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GuestOs defines model for GuestOs.
type GuestOs struct {
	// Type Guest OS image identifier, e.g. rhel-9.
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Memory defines model for Memory.
type Memory struct {
	// Size Memory allocation, e.g. 16GB.
	Size                 string                 `json:"size"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Network defines model for Network.
type Network struct {
	// IpMode How the address is procured (ADR-009 fulfillment): dynamic=allocate, static=a specific requested address, byo=a consumer-supplied existing Network.IPAddress reference.
	IpMode *NetworkIpMode `json:"ip_mode,omitempty"`

	// Mac Optional requested MAC address.
	Mac *string `json:"mac,omitempty"`

	// Name Local NIC name, e.g. eth0.
	Name *string `json:"name,omitempty"`

	// NetworkRef handle/uuid of an existing Network.VirtualNetwork the NIC attaches to (selected from the eligible set). Carried as a references->Network.VirtualNetwork relationship.
	NetworkRef string `json:"network_ref"`

	// RequestedAddress For ip_mode=static/byo: the desired/existing address (byo references an existing Network.IPAddress).
	RequestedAddress     *string                `json:"requested_address,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NetworkIpMode How the address is procured (ADR-009 fulfillment): dynamic=allocate, static=a specific requested address, byo=a consumer-supplied existing Network.IPAddress reference.
type NetworkIpMode string

// Placement Placement INTENT expressed as a SELECTION of an existing Facility.Location (populated by a platform data layer and/or a Facility.Location provider), plus affinity relative to other existing resources. Policy governs which locations a given consumer may select; the VM only references one — it does not define locations itself (ADR-009 §4: guidance, not a gate).
type Placement struct {
	// Affinity Co-location / separation intent relative to OTHER existing resources.
	Affinity *[]Affinity `json:"affinity,omitempty"`

	// LocationRef handle/uuid of an existing Facility.Location the VM is placed in — chosen from the eligible set (platform-layer + provider-advertised, policy-filtered). Also carried as a references->Facility.Location relationship.
	LocationRef *string `json:"location_ref,omitempty"`

	// Zone Sovereignty/availability zone constraint (resolved against the selected location's zone).
	Zone                 *string                `json:"zone,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Power Desired guest power state the provider drives to (KubeVirt runStrategy / Redfish PowerState). Distinct from the four-state lifecycle_state.
type Power struct {
	// DesiredState Target guest power state.
	DesiredState         *PowerDesiredState     `json:"desired_state,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PowerDesiredState Target guest power state.
type PowerDesiredState string

// VMSpec defines model for VMSpec.
type VMSpec struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`
	Disks      *[]Disk    `json:"disks,omitempty"`
	GuestOs    GuestOs    `json:"guest_os"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// InstanceSize Provider-neutral size class (small|medium|large, ordered/comparable — common-elements §2.2, ADR-014). Size by class IN PLACE OF vcpu+memory; the provider maps it to concrete resources at naturalization (ADR-023). anyOf enforces sizing by class OR raw.
	InstanceSize *string `json:"instance_size,omitempty"`
	Memory       *Memory `json:"memory,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Networks Network attachment INTENT — each entry SELECTS an existing Network.VirtualNetwork (platform-layer and/or provider-advertised) the NIC attaches to; the responsible network provider + policy decide eligibility. The VM references existing networks, it does not define network segments itself.
	Networks *[]Network `json:"networks,omitempty"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// Placement Placement INTENT expressed as a SELECTION of an existing Facility.Location (populated by a platform data layer and/or a Facility.Location provider), plus affinity relative to other existing resources. Policy governs which locations a given consumer may select; the VM only references one — it does not define locations itself (ADR-009 §4: guidance, not a gate).
	Placement *Placement `json:"placement,omitempty"`

	// Power Desired guest power state the provider drives to (KubeVirt runStrategy / Redfish PowerState). Distinct from the four-state lifecycle_state.
	Power *Power `json:"power,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime           *time.Time             `json:"update_time,omitempty"`
	Vcpu                 *Vcpu                  `json:"vcpu,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Vcpu defines model for Vcpu.
type Vcpu struct {
	// Count Number of virtual CPUs.
	Count                int                    `json:"count"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for Affinity. Returns the specified
// element and whether it was found
func (a Affinity) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Affinity
func (a *Affinity) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Affinity to handle AdditionalProperties
func (a *Affinity) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["rule"]; found {
		err = json.Unmarshal(raw, &a.Rule)
		if err != nil {
			return fmt.Errorf("error reading 'rule': %w", err)
		}
		delete(object, "rule")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Affinity to handle AdditionalProperties
func (a Affinity) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["rule"], err = json.Marshal(a.Rule)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'rule': %w", err)
	}

	object["target"], err = json.Marshal(a.Target)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'target': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Disk. Returns the specified
// element and whether it was found
func (a Disk) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Disk
func (a *Disk) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Disk to handle AdditionalProperties
func (a *Disk) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if raw, found := object["storage_class"]; found {
		err = json.Unmarshal(raw, &a.StorageClass)
		if err != nil {
			return fmt.Errorf("error reading 'storage_class': %w", err)
		}
		delete(object, "storage_class")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Disk to handle AdditionalProperties
func (a Disk) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	if a.StorageClass != nil {
		object["storage_class"], err = json.Marshal(a.StorageClass)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage_class': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for GuestOs. Returns the specified
// element and whether it was found
func (a GuestOs) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GuestOs
func (a *GuestOs) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GuestOs to handle AdditionalProperties
func (a *GuestOs) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GuestOs to handle AdditionalProperties
func (a GuestOs) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Memory. Returns the specified
// element and whether it was found
func (a Memory) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Memory
func (a *Memory) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a *Memory) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a Memory) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Network. Returns the specified
// element and whether it was found
func (a Network) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Network
func (a *Network) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a *Network) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ip_mode"]; found {
		err = json.Unmarshal(raw, &a.IpMode)
		if err != nil {
			return fmt.Errorf("error reading 'ip_mode': %w", err)
		}
		delete(object, "ip_mode")
	}

	if raw, found := object["mac"]; found {
		err = json.Unmarshal(raw, &a.Mac)
		if err != nil {
			return fmt.Errorf("error reading 'mac': %w", err)
		}
		delete(object, "mac")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["network_ref"]; found {
		err = json.Unmarshal(raw, &a.NetworkRef)
		if err != nil {
			return fmt.Errorf("error reading 'network_ref': %w", err)
		}
		delete(object, "network_ref")
	}

	if raw, found := object["requested_address"]; found {
		err = json.Unmarshal(raw, &a.RequestedAddress)
		if err != nil {
			return fmt.Errorf("error reading 'requested_address': %w", err)
		}
		delete(object, "requested_address")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a Network) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.IpMode != nil {
		object["ip_mode"], err = json.Marshal(a.IpMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip_mode': %w", err)
		}
	}

	if a.Mac != nil {
		object["mac"], err = json.Marshal(a.Mac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mac': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	object["network_ref"], err = json.Marshal(a.NetworkRef)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'network_ref': %w", err)
	}

	if a.RequestedAddress != nil {
		object["requested_address"], err = json.Marshal(a.RequestedAddress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'requested_address': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Placement. Returns the specified
// element and whether it was found
func (a Placement) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Placement
func (a *Placement) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Placement to handle AdditionalProperties
func (a *Placement) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["affinity"]; found {
		err = json.Unmarshal(raw, &a.Affinity)
		if err != nil {
			return fmt.Errorf("error reading 'affinity': %w", err)
		}
		delete(object, "affinity")
	}

	if raw, found := object["location_ref"]; found {
		err = json.Unmarshal(raw, &a.LocationRef)
		if err != nil {
			return fmt.Errorf("error reading 'location_ref': %w", err)
		}
		delete(object, "location_ref")
	}

	if raw, found := object["zone"]; found {
		err = json.Unmarshal(raw, &a.Zone)
		if err != nil {
			return fmt.Errorf("error reading 'zone': %w", err)
		}
		delete(object, "zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Placement to handle AdditionalProperties
func (a Placement) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Affinity != nil {
		object["affinity"], err = json.Marshal(a.Affinity)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'affinity': %w", err)
		}
	}

	if a.LocationRef != nil {
		object["location_ref"], err = json.Marshal(a.LocationRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location_ref': %w", err)
		}
	}

	if a.Zone != nil {
		object["zone"], err = json.Marshal(a.Zone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'zone': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Power. Returns the specified
// element and whether it was found
func (a Power) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Power
func (a *Power) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Power to handle AdditionalProperties
func (a *Power) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["desired_state"]; found {
		err = json.Unmarshal(raw, &a.DesiredState)
		if err != nil {
			return fmt.Errorf("error reading 'desired_state': %w", err)
		}
		delete(object, "desired_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Power to handle AdditionalProperties
func (a Power) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DesiredState != nil {
		object["desired_state"], err = json.Marshal(a.DesiredState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'desired_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VMSpec. Returns the specified
// element and whether it was found
func (a VMSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VMSpec
func (a *VMSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a *VMSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["disks"]; found {
		err = json.Unmarshal(raw, &a.Disks)
		if err != nil {
			return fmt.Errorf("error reading 'disks': %w", err)
		}
		delete(object, "disks")
	}

	if raw, found := object["guest_os"]; found {
		err = json.Unmarshal(raw, &a.GuestOs)
		if err != nil {
			return fmt.Errorf("error reading 'guest_os': %w", err)
		}
		delete(object, "guest_os")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["instance_size"]; found {
		err = json.Unmarshal(raw, &a.InstanceSize)
		if err != nil {
			return fmt.Errorf("error reading 'instance_size': %w", err)
		}
		delete(object, "instance_size")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["networks"]; found {
		err = json.Unmarshal(raw, &a.Networks)
		if err != nil {
			return fmt.Errorf("error reading 'networks': %w", err)
		}
		delete(object, "networks")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["placement"]; found {
		err = json.Unmarshal(raw, &a.Placement)
		if err != nil {
			return fmt.Errorf("error reading 'placement': %w", err)
		}
		delete(object, "placement")
	}

	if raw, found := object["power"]; found {
		err = json.Unmarshal(raw, &a.Power)
		if err != nil {
			return fmt.Errorf("error reading 'power': %w", err)
		}
		delete(object, "power")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["vcpu"]; found {
		err = json.Unmarshal(raw, &a.Vcpu)
		if err != nil {
			return fmt.Errorf("error reading 'vcpu': %w", err)
		}
		delete(object, "vcpu")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a VMSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Disks != nil {
		object["disks"], err = json.Marshal(a.Disks)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'disks': %w", err)
		}
	}

	object["guest_os"], err = json.Marshal(a.GuestOs)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'guest_os': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.InstanceSize != nil {
		object["instance_size"], err = json.Marshal(a.InstanceSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_size': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Networks != nil {
		object["networks"], err = json.Marshal(a.Networks)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'networks': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.Placement != nil {
		object["placement"], err = json.Marshal(a.Placement)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'placement': %w", err)
		}
	}

	if a.Power != nil {
		object["power"], err = json.Marshal(a.Power)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'power': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	if a.Vcpu != nil {
		object["vcpu"], err = json.Marshal(a.Vcpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vcpu': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Vcpu. Returns the specified
// element and whether it was found
func (a Vcpu) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Vcpu
func (a *Vcpu) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Vcpu to handle AdditionalProperties
func (a *Vcpu) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &a.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
		delete(object, "count")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Vcpu to handle AdditionalProperties
func (a Vcpu) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["count"], err = json.Marshal(a.Count)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'count': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
