// Package vm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package vm

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AffinityRule.
const (
	AffinityRuleAffinity     AffinityRule = "affinity"
	AffinityRuleAntiAffinity AffinityRule = "anti_affinity"
)

// Valid indicates whether the value is a known member of the AffinityRule enum.
func (e AffinityRule) Valid() bool {
	switch e {
	case AffinityRuleAffinity:
		return true
	case AffinityRuleAntiAffinity:
		return true
	default:
		return false
	}
}

// Defines values for FirmwareType.
const (
	Legacy FirmwareType = "legacy"
	Uefi   FirmwareType = "uefi"
)

// Valid indicates whether the value is a known member of the FirmwareType enum.
func (e FirmwareType) Valid() bool {
	switch e {
	case Legacy:
		return true
	case Uefi:
		return true
	default:
		return false
	}
}

// Defines values for RunStateDesiredState.
const (
	Running   RunStateDesiredState = "running"
	Stopped   RunStateDesiredState = "stopped"
	Suspended RunStateDesiredState = "suspended"
)

// Valid indicates whether the value is a known member of the RunStateDesiredState enum.
func (e RunStateDesiredState) Valid() bool {
	switch e {
	case Running:
		return true
	case Stopped:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Affinity defines model for Affinity.
type Affinity struct {
	Rule AffinityRule `json:"rule"`

	// Selector Alternative to a handle: match target(s) by labels (key/value).
	Selector *map[string]interface{} `json:"selector,omitempty"`

	// Target Handle OR label-selector of an existing resource to co-locate with / avoid, resolved at reserve (DCM ADR-025/AEP-124) - you do not need its UUID in advance.
	Target               string                 `json:"target"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AffinityRule defines model for Affinity.Rule.
type AffinityRule string

// Cpu Redeclared at VM scope to TIGHTEN the base shape (required sub-fields) — tighten at your scope; BareMetalHost keeps the loose base shape verbatim.
type Cpu struct {
	// CoresPerSocket Optional topology hint: cores per socket. Provider-support-dependent.
	CoresPerSocket *int `json:"cores_per_socket,omitempty"`

	// Count Total virtual CPUs. The provider naturalizes this to its native cpu model (a KubeVirt domain cpu, a hypervisor platform's sockets*cores, a public cloud's vCPUs) at realization (DCM ADR-023).
	Count int `json:"count"`

	// Sockets Optional topology hint: sockets. Provider-support-dependent; ignored where not applicable.
	Sockets              *int                   `json:"sockets,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Firmware Guest firmware surface (Redfish Boot.BootSourceOverrideMode, KubeVirt firmware/TPM, cloud UEFI/trusted-launch). Required by modern guests (Win11-class needs uefi + secure_boot + vtpm).
type Firmware struct {
	// SecureBoot UEFI Secure Boot. Only valid with type: uefi (policy-validated).
	SecureBoot *bool `json:"secure_boot,omitempty"`

	// Type Firmware interface presented to the guest (Redfish spelling; `legacy` is BIOS).
	Type *FirmwareType `json:"type,omitempty"`

	// Vtpm Virtual TPM 2.0 device presented to the guest.
	Vtpm                 *bool                  `json:"vtpm,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FirmwareType Firmware interface presented to the guest (Redfish spelling; `legacy` is BIOS).
type FirmwareType string

// GuestOsInline defines model for GuestOsInline.
type GuestOsInline struct {
	// Type Inline OS identifier (e.g. linux-server-9). portability_breaking: a value with no os_image vocabulary entry — a review finding.
	Type string `json:"type"`

	// Version Inline OS version (e.g. 9.4).
	Version              *string                `json:"version,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Hugepages Optional huge-page backing (provider-support-dependent; validated against provider capability).
type Hugepages struct {
	Enabled *bool `json:"enabled,omitempty"`

	// PageSize e.g. 2Mi, 1Gi.
	PageSize             *string                `json:"page_size,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Memory Redeclared at VM scope to TIGHTEN the base shape (required sub-fields) — tighten at your scope; BareMetalHost keeps the loose base shape verbatim.
type Memory struct {
	// Hugepages Optional huge-page backing (provider-support-dependent; validated against provider capability).
	Hugepages *Hugepages `json:"hugepages,omitempty"`

	// Size Memory allocation, e.g. 16GB or 16Gi (class-aligned quantity pattern — Machine Base Class `memory.size`).
	Size                 string                 `json:"size"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Network defines model for Network.
type Network struct {
	// IpAddressRef A pre-allocated Network.IPAddress to bind to this interface (optional — omitted means the address service allocates at realization). Common-elements Reference shape.
	IpAddressRef *string `json:"ip_address_ref,omitempty"`

	// Mac Optional requested MAC address.
	Mac *string `json:"mac,omitempty"`

	// Name Local NIC name, e.g. eth0.
	Name *string `json:"name,omitempty"`

	// NetworkRef The Network.VirtualNetwork this interface attaches to — common-elements Reference (handle string or {uuid, handle} object); resolvable, policy-walkable, never an opaque string.
	NetworkRef *string `json:"network_ref,omitempty"`

	// Subnet REQUIREMENT — WHICH IP NETWORK, as a reference to a `Network.Subnet`. Layer 3, and INDEPENDENTLY SELECTABLE from `vlan` (layer 2): a subnet usually sits on a segment, but one segment may carry several subnets and a cloud may expose no segment at all, so the mapping is not concrete (maintainer ruling 2026-08-10). "Put me on 198.51.100.0/24" and "put me on VLAN 3020" are different requests; a consumer may state either, both, or neither.
	Subnet *string `json:"subnet,omitempty"`

	// Tier REQUIREMENT — the governed `network_tier` (performance) this attachment needs. Independent of `vlan`: which logical network and how good it is are different questions, and a consumer may state either, both, or neither. Each term denotes a floor, so any network meeting it qualifies — name-selectable but requirements-authoritative (ADR-036).
	//
	// Constraint (UDLM allOf): reference_data_type = network_tier.
	Tier *string `json:"tier,omitempty"`

	// Vlan REQUIREMENT — WHICH LOGICAL NETWORK, as a reference to a `Network.VLAN`. The VLAN is the identity of a logical network (maintainer ruling 2026-08-10): a segment id under an encapsulation, which is what an operator means by "put it on that network". Stated when the attachment must land on a specific logical network — because it has to reach something already there, or an existing application lives on it. Absent means policy decides. REALIZATION VARIES; THE AXIS DOES NOT. `Network.VLAN.encapsulation` already carries vlan / vxlan / geneve / flat, so the class is a SEGMENT of which 802.1Q is one form. A public cloud exposes no VLAN — there the segment is a VPC subnet, adopted by reference on Network.VLAN rather than given a parallel class: the VPC is the Network.VirtualNetwork and the subnet is the addressed segment within it. A consumer states the segment; which encapsulation realizes it is the provider's. Resolved against the `segment` relationship a Network.VirtualNetwork already declares, so placement narrows to networks on that segment rather than requiring the consumer to know which provider network carries it.
	Vlan *string `json:"vlan,omitempty"`

	// Zone REQUIREMENT — the network CATEGORY this attachment needs (DMZ, management, internal), as a governed taxonomy term. Independent of `vlan` and `tier`: which logical network, what kind of network, and how good it is are three different questions, and a consumer may state any, all, or none of them. FOR PLACEMENT ONLY. Requiring the management zone does not grant access to it, and nothing critical may hang off the category directly — anything required because of a zone is enforced by a policy reading it (maintainer ruling 2026-08-10). A zero-trust posture derives no trust from network location (NIST SP 800-207).
	//
	// Constraint (UDLM allOf): reference_data_type = network_zone.
	Zone                 *string                `json:"zone,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Placement Placement INTENT expressed as a SELECTION of an existing Facility.Location (populated by a platform data layer and/or a Facility.Location provider), plus affinity relative to other existing resources. Policy governs which locations a given consumer may select; the VM only references one — it does not define locations itself (DCM ADR-009 §4: guidance, not a gate).
type Placement struct {
	// Affinity Co-location / separation intent relative to OTHER named resources (not nodes). Each target is resolved at reserve, so a pre-known UUID is not required.
	Affinity *[]Affinity `json:"affinity,omitempty"`

	// LocationRef handle/uuid of an existing Facility.Location the VM is placed in — chosen from the eligible set (platform-layer + provider-advertised, policy-filtered). Also carried as a references->Facility.Location relationship.
	LocationRef *string `json:"location_ref,omitempty"`

	// Zone Availability/sovereignty zone constraint, selected from the zones the provider advertises for the chosen location; resolved against that location.
	Zone                 *string                `json:"zone,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RunState Desired guest RUN state the provider drives to (e.g. KubeVirt runStrategy). Distinct from the four-state lifecycle_state; snapshot/restore are separate operations, not run states. The discovered counterpart is outputs.observed_run_state.
type RunState struct {
	// DesiredState Target guest run state.
	DesiredState         *RunStateDesiredState  `json:"desired_state,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RunStateDesiredState Target guest run state.
type RunStateDesiredState string

// Storage The reference-discipline storage requirements descriptor (PVD-001, Machine Base Class shape) — numeric minima the realizing storage must meet. The requested performance class is the governed `storage_tier` element, not an inline enum here.
type Storage struct {
	Encryption           *bool                  `json:"encryption,omitempty"`
	MinIops              *int                   `json:"min_iops,omitempty"`
	MinReplication       *int                   `json:"min_replication,omitempty"`
	MinThroughputMbps    *int                   `json:"min_throughput_mbps,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VMSpec defines model for VMSpec.
type VMSpec struct {
	// BootOrder Ordered boot device preference (VM-specific; not meaningful for BareMetal or Container).
	BootOrder *[]string `json:"boot_order,omitempty"`

	// Cpu Redeclared at VM scope to TIGHTEN the base shape (required sub-fields) — tighten at your scope; BareMetalHost keeps the loose base shape verbatim.
	Cpu *Cpu `json:"cpu,omitempty"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Firmware Guest firmware surface (Redfish Boot.BootSourceOverrideMode, KubeVirt firmware/TPM, cloud UEFI/trusted-launch). Required by modern guests (Win11-class needs uefi + secure_boot + vtpm).
	Firmware *Firmware `json:"firmware,omitempty"`

	// GuestOs Guest operating system. Portable form is a reference to an os_image reference-data vocabulary (DCM ADR-012; layering §3.7) the target provider advertises via capability discovery (ADR-PROV-002); policy validates membership at request. Inline is the portability_breaking escape. Optional at the data layer (bare-instantiation philosophy): a VM may be declared by sizing alone; a profile MAY require it.
	GuestOs *VMSpec_GuestOs `json:"guest_os,omitempty"`

	// Hostname Realized guest hostname (FQDN where the realm provides one).
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	Hostname *string `json:"hostname,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// InstanceSize Provider-neutral size class (small|medium|large, ordered/comparable — common-elements §2.2, ADR-014). Size by class IN PLACE OF cpu+memory; the provider maps it to concrete resources at naturalization (DCM ADR-023). anyOf enforces sizing by class OR raw.
	InstanceSize *string `json:"instance_size,omitempty"`

	// IpAddresses Assigned guest IP addresses (all interfaces), IPv4-first ordering. The canonical binding surface for LB backend pools, DNS records, and monitoring targets.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	IpAddresses *[]string `json:"ip_addresses,omitempty"`

	// LayoutRef The Storage.Layout this VM realizes — handle/uuid reference to an existing Storage.Layout whose entries describe the VM's disks (per-disk shape, boot designation, storage tier). Common-elements Reference (handle string or {uuid, handle} object), following the location_ref/network_ref precedent. Also carried as a references->Storage.Layout relationship (storage_layout).
	LayoutRef *string `json:"layout_ref,omitempty"`

	// MacAddresses Realized MAC per interface, ordered as spec.networks[]. Binding surface for DHCP reservation and switch-port records.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	MacAddresses *[]string `json:"mac_addresses,omitempty"`

	// Memory Redeclared at VM scope to TIGHTEN the base shape (required sub-fields) — tighten at your scope; BareMetalHost keeps the loose base shape verbatim.
	Memory *Memory `json:"memory,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Networks Network attachment INTENT — name-selectable but requirements-authoritative (ADR-036). Select a network by `network_ref`, or state `zone`/`requires` and let placement converge on one. Neither is required; unstated, policy decides. Explicit requirements are authoritative over a name.
	Networks *[]Network `json:"networks,omitempty"`

	// ObservedRunState Observed run state at last reconciliation (running|stopped|suspended) — the discovered counterpart of spec.run_state.desired_state. Renamed from `run_state` (0.7.0) so desired (spec) and observed (outputs) never share a name.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	ObservedRunState *string `json:"observed_run_state,omitempty"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// Placement Placement INTENT expressed as a SELECTION of an existing Facility.Location (populated by a platform data layer and/or a Facility.Location provider), plus affinity relative to other existing resources. Policy governs which locations a given consumer may select; the VM only references one — it does not define locations itself (DCM ADR-009 §4: guidance, not a gate).
	Placement *Placement `json:"placement,omitempty"`

	// PrimaryIp The primary/management address — first of ip_addresses; the single-address convenience most bindings want.
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	PrimaryIp *string `json:"primary_ip,omitempty"`

	// ProviderHandle The provider-native identifier of the realized VM (opaque; correlation/ops use only — never a portable reference).
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	ProviderHandle *string `json:"provider_handle,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// RunState Desired guest RUN state the provider drives to (e.g. KubeVirt runStrategy). Distinct from the four-state lifecycle_state; snapshot/restore are separate operations, not run states. The discovered counterpart is outputs.observed_run_state.
	RunState *RunState `json:"run_state,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// Storage The reference-discipline storage requirements descriptor (PVD-001, Machine Base Class shape) — numeric minima the realizing storage must meet. The requested performance class is the governed `storage_tier` element, not an inline enum here.
	Storage *Storage `json:"storage,omitempty"`

	// StorageTier The requested storage performance class — a GOVERNED vocabulary (ADR-038 §2): canonical terms are `storage_tier` reference-data records (standard/performance/archive), each denoting a requirements floor. Name-selectable but requirements-authoritative (ADR-036); profile decides bare string vs data_reference (ADR-007/ADR-039). Mirrors the Machine Base Class `storage_tier` element. Governed vocabulary `storage_tier` (ADR-038 §2); name-selectable but requirements-authoritative (ADR-036). Profile decides bare-vs-reference.
	StorageTier *string `json:"storage_tier,omitempty"`

	// TargetSegment Realize-time placement fact (ADR-011 two-phase reserve): a reference to the Network.VLAN segment the reserved/realized placement can reach (adopt-not-absorb — the segment id/encapsulation live on the Network.VLAN). This is the declarable binding source for a fulfillment:provider dependency whose criteria are simply the target segment — e.g. a Network.IPAddress allocated on the reachable segment (DCM ADR-009 §3 worked example: bind target_segment -> the IP request's segment_ref). It is a shared-reference fact, NOT the vNIC/MAC/host-networking (those are the VM provider's own internal facts, never cross-provider criteria).
	//
	// UDLM realized output: populated by the provider when the resource reaches Realized; read-only on the request.
	TargetSegment *string `json:"target_segment,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime           *time.Time             `json:"update_time,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VMSpecGuestOs1 Constraint (UDLM allOf): reference_data_type = os_image.
type VMSpecGuestOs1 = string

// VMSpec_GuestOs Guest operating system. Portable form is a reference to an os_image reference-data vocabulary (DCM ADR-012; layering §3.7) the target provider advertises via capability discovery (ADR-PROV-002); policy validates membership at request. Inline is the portability_breaking escape. Optional at the data layer (bare-instantiation philosophy): a VM may be declared by sizing alone; a profile MAY require it.
type VMSpec_GuestOs struct {
	union json.RawMessage
}

// Getter for additional properties for Affinity. Returns the specified
// element and whether it was found
func (a Affinity) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Affinity
func (a *Affinity) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Affinity to handle AdditionalProperties
func (a *Affinity) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["rule"]; found {
		err = json.Unmarshal(raw, &a.Rule)
		if err != nil {
			return fmt.Errorf("error reading 'rule': %w", err)
		}
		delete(object, "rule")
	}

	if raw, found := object["selector"]; found {
		err = json.Unmarshal(raw, &a.Selector)
		if err != nil {
			return fmt.Errorf("error reading 'selector': %w", err)
		}
		delete(object, "selector")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Affinity to handle AdditionalProperties
func (a Affinity) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["rule"], err = json.Marshal(a.Rule)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'rule': %w", err)
	}

	if a.Selector != nil {
		object["selector"], err = json.Marshal(a.Selector)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'selector': %w", err)
		}
	}

	object["target"], err = json.Marshal(a.Target)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'target': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Cpu. Returns the specified
// element and whether it was found
func (a Cpu) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Cpu
func (a *Cpu) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Cpu to handle AdditionalProperties
func (a *Cpu) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cores_per_socket"]; found {
		err = json.Unmarshal(raw, &a.CoresPerSocket)
		if err != nil {
			return fmt.Errorf("error reading 'cores_per_socket': %w", err)
		}
		delete(object, "cores_per_socket")
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &a.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
		delete(object, "count")
	}

	if raw, found := object["sockets"]; found {
		err = json.Unmarshal(raw, &a.Sockets)
		if err != nil {
			return fmt.Errorf("error reading 'sockets': %w", err)
		}
		delete(object, "sockets")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Cpu to handle AdditionalProperties
func (a Cpu) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CoresPerSocket != nil {
		object["cores_per_socket"], err = json.Marshal(a.CoresPerSocket)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cores_per_socket': %w", err)
		}
	}

	object["count"], err = json.Marshal(a.Count)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'count': %w", err)
	}

	if a.Sockets != nil {
		object["sockets"], err = json.Marshal(a.Sockets)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sockets': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Firmware. Returns the specified
// element and whether it was found
func (a Firmware) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Firmware
func (a *Firmware) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Firmware to handle AdditionalProperties
func (a *Firmware) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["secure_boot"]; found {
		err = json.Unmarshal(raw, &a.SecureBoot)
		if err != nil {
			return fmt.Errorf("error reading 'secure_boot': %w", err)
		}
		delete(object, "secure_boot")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["vtpm"]; found {
		err = json.Unmarshal(raw, &a.Vtpm)
		if err != nil {
			return fmt.Errorf("error reading 'vtpm': %w", err)
		}
		delete(object, "vtpm")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Firmware to handle AdditionalProperties
func (a Firmware) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SecureBoot != nil {
		object["secure_boot"], err = json.Marshal(a.SecureBoot)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'secure_boot': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Vtpm != nil {
		object["vtpm"], err = json.Marshal(a.Vtpm)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vtpm': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for GuestOsInline. Returns the specified
// element and whether it was found
func (a GuestOsInline) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GuestOsInline
func (a *GuestOsInline) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GuestOsInline to handle AdditionalProperties
func (a *GuestOsInline) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GuestOsInline to handle AdditionalProperties
func (a GuestOsInline) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	if a.Version != nil {
		object["version"], err = json.Marshal(a.Version)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'version': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Hugepages. Returns the specified
// element and whether it was found
func (a Hugepages) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Hugepages
func (a *Hugepages) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Hugepages to handle AdditionalProperties
func (a *Hugepages) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["enabled"]; found {
		err = json.Unmarshal(raw, &a.Enabled)
		if err != nil {
			return fmt.Errorf("error reading 'enabled': %w", err)
		}
		delete(object, "enabled")
	}

	if raw, found := object["page_size"]; found {
		err = json.Unmarshal(raw, &a.PageSize)
		if err != nil {
			return fmt.Errorf("error reading 'page_size': %w", err)
		}
		delete(object, "page_size")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Hugepages to handle AdditionalProperties
func (a Hugepages) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Enabled != nil {
		object["enabled"], err = json.Marshal(a.Enabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enabled': %w", err)
		}
	}

	if a.PageSize != nil {
		object["page_size"], err = json.Marshal(a.PageSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'page_size': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Memory. Returns the specified
// element and whether it was found
func (a Memory) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Memory
func (a *Memory) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a *Memory) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["hugepages"]; found {
		err = json.Unmarshal(raw, &a.Hugepages)
		if err != nil {
			return fmt.Errorf("error reading 'hugepages': %w", err)
		}
		delete(object, "hugepages")
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a Memory) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Hugepages != nil {
		object["hugepages"], err = json.Marshal(a.Hugepages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hugepages': %w", err)
		}
	}

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Network. Returns the specified
// element and whether it was found
func (a Network) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Network
func (a *Network) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a *Network) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ip_address_ref"]; found {
		err = json.Unmarshal(raw, &a.IpAddressRef)
		if err != nil {
			return fmt.Errorf("error reading 'ip_address_ref': %w", err)
		}
		delete(object, "ip_address_ref")
	}

	if raw, found := object["mac"]; found {
		err = json.Unmarshal(raw, &a.Mac)
		if err != nil {
			return fmt.Errorf("error reading 'mac': %w", err)
		}
		delete(object, "mac")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["network_ref"]; found {
		err = json.Unmarshal(raw, &a.NetworkRef)
		if err != nil {
			return fmt.Errorf("error reading 'network_ref': %w", err)
		}
		delete(object, "network_ref")
	}

	if raw, found := object["subnet"]; found {
		err = json.Unmarshal(raw, &a.Subnet)
		if err != nil {
			return fmt.Errorf("error reading 'subnet': %w", err)
		}
		delete(object, "subnet")
	}

	if raw, found := object["tier"]; found {
		err = json.Unmarshal(raw, &a.Tier)
		if err != nil {
			return fmt.Errorf("error reading 'tier': %w", err)
		}
		delete(object, "tier")
	}

	if raw, found := object["vlan"]; found {
		err = json.Unmarshal(raw, &a.Vlan)
		if err != nil {
			return fmt.Errorf("error reading 'vlan': %w", err)
		}
		delete(object, "vlan")
	}

	if raw, found := object["zone"]; found {
		err = json.Unmarshal(raw, &a.Zone)
		if err != nil {
			return fmt.Errorf("error reading 'zone': %w", err)
		}
		delete(object, "zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a Network) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.IpAddressRef != nil {
		object["ip_address_ref"], err = json.Marshal(a.IpAddressRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip_address_ref': %w", err)
		}
	}

	if a.Mac != nil {
		object["mac"], err = json.Marshal(a.Mac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mac': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.NetworkRef != nil {
		object["network_ref"], err = json.Marshal(a.NetworkRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'network_ref': %w", err)
		}
	}

	if a.Subnet != nil {
		object["subnet"], err = json.Marshal(a.Subnet)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subnet': %w", err)
		}
	}

	if a.Tier != nil {
		object["tier"], err = json.Marshal(a.Tier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tier': %w", err)
		}
	}

	if a.Vlan != nil {
		object["vlan"], err = json.Marshal(a.Vlan)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vlan': %w", err)
		}
	}

	if a.Zone != nil {
		object["zone"], err = json.Marshal(a.Zone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'zone': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Placement. Returns the specified
// element and whether it was found
func (a Placement) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Placement
func (a *Placement) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Placement to handle AdditionalProperties
func (a *Placement) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["affinity"]; found {
		err = json.Unmarshal(raw, &a.Affinity)
		if err != nil {
			return fmt.Errorf("error reading 'affinity': %w", err)
		}
		delete(object, "affinity")
	}

	if raw, found := object["location_ref"]; found {
		err = json.Unmarshal(raw, &a.LocationRef)
		if err != nil {
			return fmt.Errorf("error reading 'location_ref': %w", err)
		}
		delete(object, "location_ref")
	}

	if raw, found := object["zone"]; found {
		err = json.Unmarshal(raw, &a.Zone)
		if err != nil {
			return fmt.Errorf("error reading 'zone': %w", err)
		}
		delete(object, "zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Placement to handle AdditionalProperties
func (a Placement) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Affinity != nil {
		object["affinity"], err = json.Marshal(a.Affinity)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'affinity': %w", err)
		}
	}

	if a.LocationRef != nil {
		object["location_ref"], err = json.Marshal(a.LocationRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location_ref': %w", err)
		}
	}

	if a.Zone != nil {
		object["zone"], err = json.Marshal(a.Zone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'zone': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RunState. Returns the specified
// element and whether it was found
func (a RunState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RunState
func (a *RunState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RunState to handle AdditionalProperties
func (a *RunState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["desired_state"]; found {
		err = json.Unmarshal(raw, &a.DesiredState)
		if err != nil {
			return fmt.Errorf("error reading 'desired_state': %w", err)
		}
		delete(object, "desired_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RunState to handle AdditionalProperties
func (a RunState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DesiredState != nil {
		object["desired_state"], err = json.Marshal(a.DesiredState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'desired_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Storage. Returns the specified
// element and whether it was found
func (a Storage) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Storage
func (a *Storage) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Storage to handle AdditionalProperties
func (a *Storage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["encryption"]; found {
		err = json.Unmarshal(raw, &a.Encryption)
		if err != nil {
			return fmt.Errorf("error reading 'encryption': %w", err)
		}
		delete(object, "encryption")
	}

	if raw, found := object["min_iops"]; found {
		err = json.Unmarshal(raw, &a.MinIops)
		if err != nil {
			return fmt.Errorf("error reading 'min_iops': %w", err)
		}
		delete(object, "min_iops")
	}

	if raw, found := object["min_replication"]; found {
		err = json.Unmarshal(raw, &a.MinReplication)
		if err != nil {
			return fmt.Errorf("error reading 'min_replication': %w", err)
		}
		delete(object, "min_replication")
	}

	if raw, found := object["min_throughput_mbps"]; found {
		err = json.Unmarshal(raw, &a.MinThroughputMbps)
		if err != nil {
			return fmt.Errorf("error reading 'min_throughput_mbps': %w", err)
		}
		delete(object, "min_throughput_mbps")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Storage to handle AdditionalProperties
func (a Storage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Encryption != nil {
		object["encryption"], err = json.Marshal(a.Encryption)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'encryption': %w", err)
		}
	}

	if a.MinIops != nil {
		object["min_iops"], err = json.Marshal(a.MinIops)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'min_iops': %w", err)
		}
	}

	if a.MinReplication != nil {
		object["min_replication"], err = json.Marshal(a.MinReplication)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'min_replication': %w", err)
		}
	}

	if a.MinThroughputMbps != nil {
		object["min_throughput_mbps"], err = json.Marshal(a.MinThroughputMbps)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'min_throughput_mbps': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VMSpec. Returns the specified
// element and whether it was found
func (a VMSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VMSpec
func (a *VMSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a *VMSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["boot_order"]; found {
		err = json.Unmarshal(raw, &a.BootOrder)
		if err != nil {
			return fmt.Errorf("error reading 'boot_order': %w", err)
		}
		delete(object, "boot_order")
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["firmware"]; found {
		err = json.Unmarshal(raw, &a.Firmware)
		if err != nil {
			return fmt.Errorf("error reading 'firmware': %w", err)
		}
		delete(object, "firmware")
	}

	if raw, found := object["guest_os"]; found {
		err = json.Unmarshal(raw, &a.GuestOs)
		if err != nil {
			return fmt.Errorf("error reading 'guest_os': %w", err)
		}
		delete(object, "guest_os")
	}

	if raw, found := object["hostname"]; found {
		err = json.Unmarshal(raw, &a.Hostname)
		if err != nil {
			return fmt.Errorf("error reading 'hostname': %w", err)
		}
		delete(object, "hostname")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["instance_size"]; found {
		err = json.Unmarshal(raw, &a.InstanceSize)
		if err != nil {
			return fmt.Errorf("error reading 'instance_size': %w", err)
		}
		delete(object, "instance_size")
	}

	if raw, found := object["ip_addresses"]; found {
		err = json.Unmarshal(raw, &a.IpAddresses)
		if err != nil {
			return fmt.Errorf("error reading 'ip_addresses': %w", err)
		}
		delete(object, "ip_addresses")
	}

	if raw, found := object["layout_ref"]; found {
		err = json.Unmarshal(raw, &a.LayoutRef)
		if err != nil {
			return fmt.Errorf("error reading 'layout_ref': %w", err)
		}
		delete(object, "layout_ref")
	}

	if raw, found := object["mac_addresses"]; found {
		err = json.Unmarshal(raw, &a.MacAddresses)
		if err != nil {
			return fmt.Errorf("error reading 'mac_addresses': %w", err)
		}
		delete(object, "mac_addresses")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["networks"]; found {
		err = json.Unmarshal(raw, &a.Networks)
		if err != nil {
			return fmt.Errorf("error reading 'networks': %w", err)
		}
		delete(object, "networks")
	}

	if raw, found := object["observed_run_state"]; found {
		err = json.Unmarshal(raw, &a.ObservedRunState)
		if err != nil {
			return fmt.Errorf("error reading 'observed_run_state': %w", err)
		}
		delete(object, "observed_run_state")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["placement"]; found {
		err = json.Unmarshal(raw, &a.Placement)
		if err != nil {
			return fmt.Errorf("error reading 'placement': %w", err)
		}
		delete(object, "placement")
	}

	if raw, found := object["primary_ip"]; found {
		err = json.Unmarshal(raw, &a.PrimaryIp)
		if err != nil {
			return fmt.Errorf("error reading 'primary_ip': %w", err)
		}
		delete(object, "primary_ip")
	}

	if raw, found := object["provider_handle"]; found {
		err = json.Unmarshal(raw, &a.ProviderHandle)
		if err != nil {
			return fmt.Errorf("error reading 'provider_handle': %w", err)
		}
		delete(object, "provider_handle")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["run_state"]; found {
		err = json.Unmarshal(raw, &a.RunState)
		if err != nil {
			return fmt.Errorf("error reading 'run_state': %w", err)
		}
		delete(object, "run_state")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if raw, found := object["storage_tier"]; found {
		err = json.Unmarshal(raw, &a.StorageTier)
		if err != nil {
			return fmt.Errorf("error reading 'storage_tier': %w", err)
		}
		delete(object, "storage_tier")
	}

	if raw, found := object["target_segment"]; found {
		err = json.Unmarshal(raw, &a.TargetSegment)
		if err != nil {
			return fmt.Errorf("error reading 'target_segment': %w", err)
		}
		delete(object, "target_segment")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a VMSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BootOrder != nil {
		object["boot_order"], err = json.Marshal(a.BootOrder)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'boot_order': %w", err)
		}
	}

	if a.Cpu != nil {
		object["cpu"], err = json.Marshal(a.Cpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Firmware != nil {
		object["firmware"], err = json.Marshal(a.Firmware)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firmware': %w", err)
		}
	}

	if a.GuestOs != nil {
		object["guest_os"], err = json.Marshal(a.GuestOs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'guest_os': %w", err)
		}
	}

	if a.Hostname != nil {
		object["hostname"], err = json.Marshal(a.Hostname)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hostname': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.InstanceSize != nil {
		object["instance_size"], err = json.Marshal(a.InstanceSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_size': %w", err)
		}
	}

	if a.IpAddresses != nil {
		object["ip_addresses"], err = json.Marshal(a.IpAddresses)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip_addresses': %w", err)
		}
	}

	if a.LayoutRef != nil {
		object["layout_ref"], err = json.Marshal(a.LayoutRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'layout_ref': %w", err)
		}
	}

	if a.MacAddresses != nil {
		object["mac_addresses"], err = json.Marshal(a.MacAddresses)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mac_addresses': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Networks != nil {
		object["networks"], err = json.Marshal(a.Networks)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'networks': %w", err)
		}
	}

	if a.ObservedRunState != nil {
		object["observed_run_state"], err = json.Marshal(a.ObservedRunState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'observed_run_state': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.Placement != nil {
		object["placement"], err = json.Marshal(a.Placement)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'placement': %w", err)
		}
	}

	if a.PrimaryIp != nil {
		object["primary_ip"], err = json.Marshal(a.PrimaryIp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'primary_ip': %w", err)
		}
	}

	if a.ProviderHandle != nil {
		object["provider_handle"], err = json.Marshal(a.ProviderHandle)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_handle': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	if a.RunState != nil {
		object["run_state"], err = json.Marshal(a.RunState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'run_state': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	if a.StorageTier != nil {
		object["storage_tier"], err = json.Marshal(a.StorageTier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage_tier': %w", err)
		}
	}

	if a.TargetSegment != nil {
		object["target_segment"], err = json.Marshal(a.TargetSegment)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'target_segment': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsGuestOsInline returns the union data inside the VMSpec_GuestOs as a GuestOsInline
func (t VMSpec_GuestOs) AsGuestOsInline() (GuestOsInline, error) {
	var body GuestOsInline
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGuestOsInline overwrites any union data inside the VMSpec_GuestOs as the provided GuestOsInline
func (t *VMSpec_GuestOs) FromGuestOsInline(v GuestOsInline) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGuestOsInline performs a merge with any union data inside the VMSpec_GuestOs, using the provided GuestOsInline
func (t *VMSpec_GuestOs) MergeGuestOsInline(v GuestOsInline) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVMSpecGuestOs1 returns the union data inside the VMSpec_GuestOs as a VMSpecGuestOs1
func (t VMSpec_GuestOs) AsVMSpecGuestOs1() (VMSpecGuestOs1, error) {
	var body VMSpecGuestOs1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVMSpecGuestOs1 overwrites any union data inside the VMSpec_GuestOs as the provided VMSpecGuestOs1
func (t *VMSpec_GuestOs) FromVMSpecGuestOs1(v VMSpecGuestOs1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVMSpecGuestOs1 performs a merge with any union data inside the VMSpec_GuestOs, using the provided VMSpecGuestOs1
func (t *VMSpec_GuestOs) MergeVMSpecGuestOs1(v VMSpecGuestOs1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VMSpec_GuestOs) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VMSpec_GuestOs) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
