// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9s28v8qO/x3pu389WirTqM3N66ltMzEis+Sm+lFPgcilxISEmAAULKa0Xe/WYCkRIly3F7jy9zc",
	"O5MEsA/Y/e1vV/7kBTJJpUBhtNf/5KVMsQQNKvvkC22YCNAPr5hZ0JsQdaB4argUXt+7EfxjhsBDFIZH",
	"HBXICMwCgecbvYaH9yxJY/T6XvfkFHs/nD1r4o/PZ83uSXjaZL0fzpq9k7Ozbq/7rNfpdLyGx+nklOQ1",
	"PMES2slLPbyGp/BjxhWGXt+oDBueDhaYMFIuYfevUMxJ07PThpdwUTx2G3SiQUVn//Mta/7eaT6//S7/",
	"o3n7qdM4626K99//7Ruv4Zl1SrK1UVzMvc1mQ6J1KoVG65wXUs14GKKgh0AKg8LQnyxNYx4wclH7vZb2",
	"c+kE8qBhPCbnaVQQStQgpIEFWyKkqBKuNZcCjAQWBKg1mAXXoFDLTFmHasNMpr1+r3Pa8Aw31rfnbm1U",
	"6lTqfzW8vvTHY//16G4wHPnDgbfZ9dk3CiOv7/1fexsHbfdVt4dKSeUsr9771vRNw7sRLDMLqfjvdCd/",
	"yhW/spiHQMdQILkNECi0ccViDUwhFPf+KNd0d1xTPbYMn9JDN6Pzm8kvw9HEvzif/CX+qbhkU55nw8Zt",
	"Okil6xcX8OzHzjMgOTFnwgDSSihizmt4qZIpKsNd/BXe2z/plyxhoqmQhWwWI+B9GjPhbNcpBjziAbnQ",
	"+k4GQaYU7mfqZIHwLeXetxBxjEOwbs7dP8sMrJiL2lTJJQ93nVmkS6NM2hrYuPZBYYRWMMWsU6bUzhl+",
	"RLe2/arbj0STSKqEGa/vZYo3S6F1+hbBc+DPyeQK3EcIZFjRptfplCdxYXCOio7KQ2//pPFCKgOL6v3o",
	"LEmYWhfImSo5izGpmOyLpU0QX6SZqVPdvXjYzTlIr7mYW0HOyXbnrqyFManut9thkLTyt61AJoXXuVOl",
	"yXNVHuvezS5uv/Vysc5Pt+VqOXuPgSGLxqiWPMDJOkX/aBy9yOIYtFtpLSnrTgkKoDBVqFEYmwEHSRQo",
	"ZAbvDE9qzp/wBLVhSQqrBYpKYbMZEHGlDbgjwl1nhMxg055JZrPwtYjXRbk6uLwQYySBd8cCcJAvKIKQ",
	"EiYkV1M2Frt1C85nZKf9zALDlzgVhbq6BeOLX4aDm1fDAXAREhiirlrENXzMMMPQnhDEyESWtqbixbl/",
	"uCv/DAumAe8DxBBDSNg9T7IEFBrFUbem4mo4Gvijn++url//6g+G1w/IXjFuKDZJODd6KnJsUQRWMwxk",
	"grBAFpvFGmYYSbVVwqITiQxbU7piFFlCUVaa7DU8Z4XX8PZVovD77B3x8DHkxyEZQh68QNEL/r9Bhf5a",
	"QvNZK9NaknddpBJ93jG3YlCehU06s1lc62Mx+vOK5aFw5/jgvoYjluAOftqlFe0+ZDNccmWa3ZPTWuhP",
	"MbB8JQw5ncniqx2UcErtQXl+xUXNcvU1knEsVxTFUpQa6SxNpTIYVqBqKnJOAN/9ejlOMWjAhRSGcYHK",
	"PQ6YYTOm0T1JBRdxpo37+r0L9APYPAYhY4ccD7Hz6+H54LfHXEaWhn8eMmOmDbgT/ixi7pWSamzkd3lQ",
	"UhrefZNh2izJou11bAJpOqU2fnX7U/HnHQ83dGoaZ4rFxwKexHMxz2KmHlhS2OM+F/q3qOJy2a7ftamv",
	"ia+4NoeXcMXmXJCHIeba0K2XFh0UwO0XejCY6M+x3rrSXHIQjynF1vQs8N7cpWyOd0Z+cE3SXqjQa4uZ",
	"DryXBTOhnUA7SXOFOouNroQqrl+m/7jwz/z3w/XlyU1nNPnt9NWbm97rN765nLz8cLnuLkaDm5NXk7+v",
	"R+9/ux8Nhqejwfnq8uLl81pqspdHlEgYZIqb9ZiMds6ZIVOoqJvYPr0o4vflm4m3jxEv30zA2g5yZhM7",
	"hEjJxNVPKSI+z6iC04lwtYUt62dSx4nYKkzUzHUbXESyaLVYQBFw0IIMLi5hfAUleF8yweaYEEE4v/Kh",
	"CRdEWwi0mKDKXX6VUVm/KpSKyvmEaDpt53QTtFwfL3gQxXIFTBNXscZziwdTQaqhWNAaK5ECUmoWO0yL",
	"eYDU7vQ/Fd3/ecqCBcJJi2pFpuIdlrparVrMfm5JNW/ne3X7lX8xHI2HzZNWp7UwSbxDykvoLlz+3fjq",
	"+2N+8hreEpV2Ll12WZwuWJcOkykKlnKv7522Oq2e54qnjZP6DLaf5mjq6qvJlNDAymytpbQaVtwsQKau",
	"QEHEY4M2gq02yl6mH3p9j0DB3034nZnO2wMObY8pRe6UTzuH+ZihWm8HMelemNoW+SCfjsjYWjJbV2w8",
	"Iixfcpcv+QMC/Qhs6QAtI9O0FNnGXyGfKfJrEGdhGZYF0EwFi6WYax5izqJ3MgAGGDFaRZw0YrFGF7O1",
	"2i/k6i4XXdE+dGd4fXtAmd0zKYnO1plzmfNqkSUzN2PLlYUUlUXKIzok7N5BsOa/Y70SXepgc+JePHGR",
	"Px32tofKbWE8dWXHtVm10bOtBg9d5+3eoO2k03nEXOlxI5tjNbRmiDPO7JApymIo84tSv/egOnn//v9/",
	"TK2jk6SfWGgnL6iNk909dlTpsnZ1+kSbTj+/qTLSK6Pjqcy8EXifYkBZivmahpdPRnJEA3as2SeMM2xu",
	"eVxJmG6pbZB17MgWPgQGAldbciojYJXjW1PxOsfaeJ3z/DUwCGKOwjSZ1nxOVc0fTMWSM4sh73j4DmzQ",
	"Qwm6LfCjyqys4aogyUIFKx7HMEdBAYbABPgDhylVTHdK7/SSD4J6oTj4A5uZtW47kqS8ilZfdqZ+67g8",
	"avOTDNdfMsuLAf7ubwebA6DpfnkV9ipVEX/FFOmpAaaYLbqB3tNBTK/TezojR9JAJDOR6/r86SRfSBHF",
	"PDDQLPPOHwCLqcddE/XItO2eeicnT6eU/bnFkX+8DzAtKtvXBvsFUosHYLoe+zeNYzR829L74cYVB6Jo",
	"dbQ8kcuK8Ba8WaCAd8Xs9R1wnfPMYgoLEeNxphzFnAqFgVQ5x2TluNJOWW3b5XinxT9qgm0boB3taIFt",
	"trieikxjCGFGkAkKF+tQ5dOmWK4sE2VLyUOYxTL44GZPJY13btV1FcVOlR+oKHUXul3S3vtp+JAXWl89",
	"4J3tCJssqDrHDa6RhY7rkmPIMCacPS24ecglxzl5IfKP8fFDPto7DJcSyItuQ5f0MV7/x1DdH9jxY8wL",
	"mP7vw/bS8WIX5L82KHPZtosmx0hr7YzgZzQVGJytgRsNmfsJwh8cZPfPaL5caj+mvXZZm7/OM7nX6bWm",
	"4kl66CfuIb/a/vF/QPCVAcF+Ju+N+47QmZ2JtM3g3Vn021uKdtdOuvx2M9I2S3l7O7O8LU8++HGofkxc",
	"Bq0+/Ecsb3O7+VcAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
