// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D3pchs3mq+C6pkqS5luirckTk1tKSIdc2Ido8PJxtRqwO6PJOxuoAOgKTMuVe2vfYCtfcJ5ki0AfbMp",
	"kjriTOJ/FInru09Any2XBSGjQKWwep+tEHMcgASu/zrGEvtsOpQQDL1zLGfqSw+Ey0koCaNWz7qm5OcI",
	"EPGASjIhwNGEcSRngFwzGREJgWVb8AkHoQ9WzxIB9n1nrr4kaolQLWxbFAfqVze/p2VbHH6OCAfP6kke",
	"gW0JdwYBNmeVErha4b/eY+eXunN4sxN/cG4+1+1u4z75fvc//mzZllyEen/JCZ1a9/d2AUAqJKYuPA1Q",
	"ROJlHglxeoiXhvwS+Jy4cLUIHwGxMJORXjYP6CoQRX63lwXtXq0uQkYFaB4+8jlgbzH4RIRhcZdRCVSq",
	"jzgMfeJiBe/eB6GA/pwBo9AhMfGtXh5Z6I7IGSIeejUPHEUsD3PvFcJmFwRmG4WEmA961h5wzrjYq7vd",
	"/emsO3P24bDr7HdccKA1O3CgMe0etGaT9uGBQpmQWEbC6rXrh7YlidSIvQDBIu7C8kYx/DMpQ9Hb2/Pc",
	"oBaDUHNZkOwdT3Piafd5lP+Zw8TqWX/ay1TBnvlV7A3UdIPVInPEaEWDdMFvsXcBP0cg5COx/JqA76FX",
	"Ma/cKsBeoSASElEm0RgQBKFcVON2/7DV9iYtcNrjbstpNw/Hzrg+6TjjA6/VqYPb6HaggNt6htshnWOf",
	"eIib06OcDtwUvcQs4WA+jQIF9tMR/C32UILPe9t6zfiYeB7QRyL3WgBHHgOhkTnDc0Ah8IAIQRhFkiHs",
	"uiAEkjMiEI+5rRrXB7jdgUl74nTc/bbTaWHXcRuTruMeQrvbmHjN/e6kgOtWhusjs8skhWZTDGeHdTyg",
	"BLxnQHGG03vbeoNFon0fqyZy1qSkHmZYpJbhJbVDeZ/NcDvBxAfPCTm4jHpEY+fp2H2DBcowem9bQ6o0",
	"O/aVNgVu5j0O0UcURRQ+heBK8JCGAjHXjTgHD93NiA8o5ExxGqFTbbFi2a5GfRMODsmHgw/O4bRx4Bzu",
	"w9SZdj7UnWmLHNQ7H2bdRv1DDvWdovIwQGmbCNwcZgu9YWY/A7rTgxj0onigbZ0y+ZpF1HsG21dk6lSb",
	"aKNSjdrDcac7mXamTtc76Djd9thzvOZ03/Hqk85+cwqtg/1pgavbFVyt9phoEDbFK2XSMTOejthTJtHr",
	"ZK1z5hN30YcQqAfUXTwSqWYZBHPsR3o0EpHrAnjgoXEkEUaJh4S8dC90hw2+BZZETJQOrMR5y213POhO",
	"nP3pwaFTb8yI86HZajsfO353/yCgh/UGy+O8mcN5fLBs0y+sROLz5BCeEuECPmj5fyQJYtuKeLwMGi9Q",
	"vNuATgldYfwauNkau23P6UB33zk4nEydWb3RdEjrQ7vT/ejvHxwGBYbuLiE32fG3gdoUjQqxnM2J9zTd",
	"fHl+caK0r14oVYdVWnfcarteB5zuZP/AOaxPZw5pNFvOh/bHTnffDw4O67TAps0cJsvrf1FEJodJVe41",
	"xZGcMU5+eTR7vtMuqVpGRV9mAnI56GAM+wJhDpmS2Mp/67rNlgdNz2nhTtNpNw+wg7v1joP3vWa77o3r",
	"nbZXYOFGzn8rHiiN4zalQERzID2LE1fA9X26Xjl/oWNLzkLgkhgHD4fkdg5cEEOE4qrvzA+ITbT7kPfs",
	"zPqISAH+BO1AbVqz0byB/XCGG7u1ER0GQSTx2AeEJxK4oprGVm1Ei8FyPMey81Hv/L2Kbf+igtybv5jP",
	"FWGubelV4VaSAJaPf0UCEBIHIbqbAV3OUihLYhbw0M7F62PUarUOdwuna9abXafecBqtq0a716z36vWf",
	"LNuaMB5gafUsD0tw9O4q4MbeGfUXSTi/dFiPiNDHi1uTDlhKNAjgzoQToJ6/QPFYpMZW5lhqI3qSIJh6",
	"mRtCwUjCGFCkUxdlhF8G2PdRH+bgs1CFaejdiWVbAf70FuhUzqxet2VbAaHJn40KUCZKhdxG1ANeBQme",
	"AppyFoWxKBKB9AykZ9iI0BlwovA+4SzQsF33354g18dCoJ2j/oVTP2gqNjqLZBhJh1F/8VdEQfl0AqQy",
	"Uxi5PgEqS/C917m8SIJ1Y1sKUZrNlwBYQSzMOdbWNaxMBqXOmPoZEcNThhl6CXUcvene50IK775EhOLY",
	"XGYsJwPFMZvlgdbyoAjBXadlcnJ+qYbf21ZEvMcmA2voaqbpD76nGIFlFFWcO6JklaZAVzNAwz5yMVXs",
	"zPS+2PcXSEGhdvTQnOAR/TkCvsgyFsgYCb3IXxGZaLmIjbFnp7k74GgKFDiWIBBG19fDfm1ER/Q18312",
	"J9DR4NxpNJupHdFHYXSuoGVUlOWq26nDQbted6B5OHbaDa/t4P1G12m3u91Op92u1+uNdXK2dd5vLb2j",
	"0HuagvSxkChgnkH3Bmqy02s8RU3ep9+wsfLJLNv65GAIndScZ/lRocW9Uuxu1Z+3xLtXaiD0I479stgp",
	"607oNPIxL/2UWZrk2wBTPAVeUwadsL3C4BUp9GeztcmCX23ul7a5aVbpyxrfJ9omJ82NFY1UWnV5yFjl",
	"Jq+3WrnBz6TOeERvq0zRuY9d0PjkEUXEq6Gc46DsgULG0fmwTI99tw0HkyZ2GuOW57ShM3EOcXfs1N2G",
	"14TWpI07Y6tMkOc2sgnmn8HYZhz61ep+tbpbWd2sGvm+YKlKOjTm7punmOkKDRTb6/j7Bw23k8/tr7Dg",
	"Tq4Cvbkpz2atsOlvianrFe06hU/yNsRTuJXsI1TY9iv1tZZXDpITmCcJeTUTqZm1ER0EoVwgQxBEqKdz",
	"A1n8pIZrroiHFzgBFn+f/xT89MtPP/6DnH24vpv8429/qzLdHETkmwJwqZCp4h7le1Qqk1QYddUmiam2",
	"1G7WfTnKKjFdcjh7CaFLzFZNnctY7RZBuzRaK87VKCLgaiht5MGE0IQ2hTEcJsCBujCiyuAbteoyOiHT",
	"iOOcZipyRskZreCMzNUzGw37huKr6BAfQ2zj7QXWWpciEsBv59iP4CHmUKOQGRVbn1UnNWfYiFWUD/ZO",
	"rbmWQcrYLB57DZP8wUT3KRL7cpL6OAmtocFcuRoFAD1wfcxBjCijgBhHAeOgXXcvAx7t/DP9/E8bBYSi",
	"xm4NHSFlNnxIjdWIsskENPkiAQLlZplWF7UHUMkXVVKe4XoJtNPieWpogN2ZWSmFAOFCK5Gdulwjmit7",
	"Me7pA9roYQW0DbGTkEFRKSB0aKY21lM/BvcBal/k3IASv5aIpBFMaJnmFXjWQD8kAVVYyRRVsqESWEWF",
	"wjij+0Gob4XkmFApTGwHE6yYXa9jTjCicXSVJ1viHbs5HbwRLXTDz3H+LMvyl7SQbRoU5KBN0Fs2aSMa",
	"JxA0Y4n+2EY4DHfL6in5db0JiVlE3K4RB6EoxeRMWaz4PJm8yhmWptuJg6LRhW6vEhJLGNExTJSMF8Ej",
	"wgQZylcFbykZnJ4/nw1eA0kZ9/lerGoTfplnhCqGe8BW78wDW3GdxIQCt5GHJR5jATZy/UhI9ZWQjOMp",
	"2IiCvGP84+72Jr4kw4krn4esSprTGmgRZv01SjoM0UTHbkp7qkBl/6C+j845G/sQoL4u5RnpeXN1da6C",
	"cGGcKB3pHbZMwRBdJO2KVYJU1ANJebB8qjdRgKmjIh2NafgU+pjGjQXxmkgyQ5u4UUY5VXHGTdfmaiN6",
	"ghcJOZKGGSed7sXgSIZm4IfIg3Fk/AEixHK6Z+NmviUeJLksYknmL4aZH5gxW3rEQiOQ9lgLR9qyVzAN",
	"JiNOnHTbqhMnldIlqiiqmx+RyzxAOwGW7gxE3JIU85AZUQhwdX9iegBCZauZbUyohCnoQnNcll1yK2aM",
	"SxvNilwhoiDAfFGgupbb2ohezljke4ouygoQIYFKhF3ORJ5hRDJX4KC0QAHTm3RUlpXOw8SO9fwi8UGz",
	"vc3WNAqUcG/bpmlvW6+2N+88srfsybW3b4FcOyXRww58mmGlUjeYU9UksR6WMeMbrc4i6bCJwzGdwibo",
	"J+orRatNFk/b6Tah6xwTX8nF+sEeYM8nVGHR9Ggpg5Fx+/ZMt6Fqsa1PjuJsZ465Mls6mzQ8fXf0dtg/",
	"uvju+mRwemXZ1vXp0fXVm8Hp1fD46GrQt2zr9Ozq9dn1qfp49PZicNT/z8GPw8urS8u2zgcXJ8PLy+HZ",
	"aX9wOtSjLwaXZ9cXx4PBj2+Ori/NCq+Phm8H/fOLwfHZaX94NTw7VWt9e3Zhfj67vjp7fXF0+t1A7z88",
	"OX87UKfRPw5PrwYXp0dvzdHeHQ3fHn37Vg3sD476b4eng8GPx4NBf9C3bsrGOb5QECvURL9VmecK33Ep",
	"xI0d2GXd0jc/mIA+MyTax62NqO51NAGISDLo+rdXIqlE7cQ5YkMpG9EoGCt/ZcyYD5jayJzURtqV0hWq",
	"CQKPaE/obxPsKy8nHyVPyCfwzIFKg3XWsjCWUCIJ9vdENJ2CEup0Xl4LN22LRr5hcZ361K0zGqhbg63t",
	"fHPTgyfO6KbFJewqbe3jMfglHCNC0fVw7/jt0MDKAiIleDZSgd483xuhKzqxuz6y5m4Y1VwWUTmy0L/+",
	"53/RyHrnhhE6Nl8tOYfH59fmt+U8+JIVSvBdYBxDqBJ0P8xA+/BAPZ0XErpgoFPWizyQhrt0pjs2hAof",
	"sUckDOQpJ0BWsDCsoN01SIKwSgoX8tkx562ukvWZdCiTxivUeJUM4Ywga8O6QW3aKxFBESWAgPFFTZBf",
	"4HY6Tr6TWHnzNU19UZME+Mgqu+7pQutDLK1C9UFus34x7BnzhP3znNwbrBRh//vl2Sm6NKKbD3MVWyZL",
	"a88iJd6Ox/FEoma9WXcaph9HF5BM+55ypzRhC1Kq/KgoDBmXAiVt0ii/9UdY3DHuiV6c7ggIJUEU2CjA",
	"n/SHEY0LBzZSil+PMGjRY5KPIF1dObpITEcPJUbog2DUMSiqMT7d02DsxWDkf3UylBbpshS5atWmPD8l",
	"Ti7jINBOw2l0d41UqYNbvUZX0zD+w7aCyJck9OFskido3nUtavSSIdAsvJnez/TS0tGPEwcG+6kgqQgh",
	"NFmjXKHwlYjFNaf2MTWxemIWHPRaJ0KUdJp0SA9hFf6Bp7O44v33N4mKTnbTTJK7nPF9uk7COWuXwkmO",
	"Jz525ZoXIJivNKfpDHME8QCpWNpTkOjstQAf3JX5+nj3XCa8Wro+p7mEinRBEfsnODSKPD5rXivuxCnj",
	"j7BA3+8qTZRAt2SNh5OcesTSqC74OcK+MNPt3PhXIl0Ic1DDi4C9//4mMfBEoACH781Bbt7fYLroqQXN",
	"TPO1sJOkv15NwaljIEwXxiol4zRbaSYVsRVa4twttHIGr4nYaZ4vaw+p0YdzH/GlzBKtq8Qsd+vjad08",
	"RYsSO0/F/h31aQzSfPjtNvNkacXtGnnqvdbTGnl+9x2nibewzGnGfXhIGy23PRXQ8z0sHKNxQky40S4q",
	"kp8yTn4xQmeKCr7UNYbaiH7L5CzWA9TLi38s6rWyuQQ6J5xRHdv11JGrzduGCuHBZqZYmhy1ltj7XLhW",
	"fT+iV7kgwcWUUeJiv6pxJpefLV5UL6yfu+1VFLHisOfqz30w13ysuDUrlVVol9qIHrMgYDShGaGuH3nQ",
	"Q9unmWsjeuQpd0Z5ipJxZSoWcaEEuZGQSpAU8GgMC0aVngYBlbnplS1Sm3uvsTLOcrHF+k2iVRNNr0Q5",
	"4QRMEQvxz8qxIdr4Y57meHPRiAYmW9+4JNrFHBhohNIC+cE95ce8O+khZX5sZIKAHCKnKt65ZcKOL6ao",
	"4ccJDXqIBHpUWv6wkwubKQnUhH5MqR4CfSXLRrHZyc3UCxs69rKfKfOUm6og5cxHoY/VbLUucLGr5lya",
	"k/aQi0PsErlQX56avXtIO/E24ixSgcGtD3PwFTquZloPRK6MOKA55kShJvGzciyp2VhrEEOexGAuaQ+D",
	"OfUpjqCs3oHOKevjaUEg4qOweu8/W8lR9ahOPX1eYcxY3vgLz7q/UUGTG0aa07g7IxL0ma2e9emge9tt",
	"W7ZlnIZe894UQfNs2KjQV1s25xVk82tP3r9RT17B09m6H6/Za3deqh+vYCMe249XbUT1mkvdd4Wxxaa7",
	"/E9re+0Kg0vvr7xYf46yknHDyvatOmfGbOjNkYM8ZiQIc6F7TkwWJXIlCjCNlEA+3N4zuDt5U39ke08h",
	"hsg6SkzBMiklGhlP4EW60qaB0ophi66EfOjzvO1A2lf/TrnqlblqndatCql+mGGpQdFuPpoxZZwrK2nA",
	"g+oy/Zy5eKwYd4HUILSDUaRO48RLYur5sFsrEHCGuXeHOawNK/W2dh6Eh6GvZvgcH2zYPZdic1MyVR8r",
	"acJbOtHj86gJk74SBeYd0WJOFSXe1SZ51S3CftviK5uQslcVcBB3lJgASWI+BSke3wYzT7BYSggUiyxZ",
	"J+VLVVqKlmllE5dlJ/kQc/CbqqBNgBtxIhc6gWu4YgyYAz+KDG+Yv14nhu7vP1xZS8nnH65iNcrG2v/N",
	"ReKJJw8eUiui5C65Fd9j1t6d3qJ4xdrchCZ0wpL75diVJim3LPz945O01fbE2CV0dD5M3CHdhhfHeeQX",
	"8NAdXiieNiZsRAvqNxNyEx/nG6tMeE3ohOPMR87VO+KwRG09yfwrtKO+GNAZpvFFFuWIMoF9sZueSy89",
	"omk9m3Gia8LIA0GmVC/+pz+hiywqUO78N9/klLn45pse6psQTkIQ+tr8qRN7ZKLz6DKO6dhkFRAjitDO",
	"u5MV4eT30Rg4BbVsObJEc+ZHAdjadObix11zzFyjqD7msYrtwEuVR9KjKUxPZjFQK7X9qTNqymR1Di0T",
	"PnGBCi2gcdhwFGJ3BqhZq1u2FXE/V8u+u7urYf2zriLEc8Xe2+Hx4PRy4DRr9dpMBn6uCcVawWZKwJJk",
	"YZayu7ctFgLFIbF6VqtWr7VjedQytrfi1kPvszUFWaXUtAekWTnEU0I19nwi5MrOfpGv1qT5HxXmVjeg",
	"68DA0qc2iB56Vs9SpqyiH19oYLKnFN8/yXlL3tTTnkz2qF7O28i/orBkqz8v5eV1zSbWpJrbtfBK5T3J",
	"iFMUAtdnWLFxgD8ZV0fZpsLeaeG0UdnAlFWL6ur3fL2oXCBaPvZrTaMVxFyimyaXLtkZmEQM5N0MuClt",
	"1kpN9Shrzkps4lJ6rPSOYwkvy136q6lyU3qmsFmvb/BSyGZvZay6vlPxesZlpLMzk8hP+9GUaLbNaao2",
	"SU+9l3vwT09prJ9SfKxDTWqtn1R4pq2zycmqXhrT1tx0wMVyu4KVdGqWiQotc6yT/krHULhbefsjp1aU",
	"r+NkeYphX6A5wVrOX626/fUKlTMZ2qh6EIRMAnUXVWrInKzq6tEaPXQW51PKR12lA7cRh5IElPIaWz7r",
	"eWOcOBDyW+YtXlJUkjdE8y+U3i9Ja+Plj1BivkqKJHUokcqxv8gJ8LMc8IEn54ptnmPmLVByVwAZY/7r",
	"aYZ2vbt+RunpMD3tcP204iOyalazucFmhee09Kz2pkcsvnj2TFrPqIlVtwD14L3t7ssbJemDhKouOx+M",
	"unzgolxRj5kpG+mxKlxkQ/ZWv+xcYXrbFbq+UtwMqFXi9iux+Ab8k773+Hx8Y8iymm/s9V65uXa2wq6M",
	"F4hIscLF/g7kr84Q9d+Gdk+fsPyd89d3IJ9TKfU4zBaeiqC131Hpy11xMp0CFygZG1eVMTXPmap4rIJ2",
	"tRH9LlcvUn5gvjRkrs35MDWpddPJk73QEUfFVVx+kRz5j8rrKc2qtOuWbPnVFVgrcim/bS54z5F+WZ11",
	"KbVyrMu0fM2w/CoZFlFBmouKhAqmi4qih2mCiPMqld0xVcCXi7yb4z0GYLwwxa24XraDTc0r7hnSzW/5",
	"4ldWG7ORAEB7uR91N+d3prvOZQFU9dD9Vf290C1iaa+dHffPxTfdPU3w7HZ3ZZGtChf53r/fQDrpaxpp",
	"TRrpUdmjzZNGz5Ueepa00O86G/QFs0BrfaavSZ9cxPIYl+0l0ykVflP5RdztkyYb5UqeFCY8Ojfy75YS",
	"2YhjCv8M5oXzKI9On2yRNXkZ1qh/Ee33x02KxJcG3Kr/1aZbPEWpM8DcVSpyTaT/J46+lXgCfAroXHfK",
	"6cbO/dZhd1d7I6dMgnmSJteAqdMbaboj647Y4fmeImEXW0aEjZYfyNk17vKDF32KDG0gfAme3sSPCBSq",
	"HI38v7ywT/FlpMr0CH9hn8IcIv1nTb9/GTdMXelBFDuPH5d5WdW5VXlROZ5O9H1RpSN0jkRnP8SqhEy+",
	"vepZEzK1ET1bapYr9djGLqdWcSGHOWGRSMPPuOH3iyR1zKVV/Z+aksjJzl5Tkww16vXV5/uiuZ+vqZNn",
	"1cDlLv+vqZNi6qTgJ2yaOlmh1Z47ixLfOx/2ERGrbw/dEd9PrxAhRmF1/iV/seCR+Zdhv/p61YieRELG",
	"XbWof3rpNBrNVvb2SoAl2vHZHXAXC0C6B5NGAXDimo7S2SKcARW7pfdYqq9J0TTm2CCb+++Q9ylc+fh1",
	"8z5LW1de/TS8/pvM+2TPiMT/jO2Plvwp/DPsZdetfEt7I1cuDvcLmm5duP+gelkTGi3/N/BfyyyuZfo/",
	"Vri/zEx5j2ol71w97Jyhf/33/+WfwX0lkJiBPwehX4TOo5ul9b8RNfXgwnMS2TU0obkx95JEaWD+YYnK",
	"2CG7vyWsF+S10rWzbTywR/DbczpHOUdcmHMnt5G0SOfvIb2/UfJqLLUReHOdYw+HZC+7c3Fz//8BAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
