// Package container provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package container

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// Defines values for PortProtocol.
const (
	Tcp PortProtocol = "tcp"
	Udp PortProtocol = "udp"
)

// Valid indicates whether the value is a known member of the PortProtocol enum.
func (e PortProtocol) Valid() bool {
	switch e {
	case Tcp:
		return true
	case Udp:
		return true
	default:
		return false
	}
}

// Defines values for PortVisibility.
const (
	External PortVisibility = "external"
	Internal PortVisibility = "internal"
	Loopback PortVisibility = "loopback"
)

// Valid indicates whether the value is a known member of the PortVisibility enum.
func (e PortVisibility) Valid() bool {
	switch e {
	case External:
		return true
	case Internal:
		return true
	case Loopback:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeRestartPolicy.
const (
	Always    RuntimeRestartPolicy = "always"
	Never     RuntimeRestartPolicy = "never"
	OnFailure RuntimeRestartPolicy = "on-failure"
)

// Valid indicates whether the value is a known member of the RuntimeRestartPolicy enum.
func (e RuntimeRestartPolicy) Valid() bool {
	switch e {
	case Always:
		return true
	case Never:
		return true
	case OnFailure:
		return true
	default:
		return false
	}
}

// ContainerSpec defines model for ContainerSpec.
type ContainerSpec struct {
	Args *[]string `json:"args,omitempty"`

	// Command Entrypoint override.
	Command *[]string `json:"command,omitempty"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Image The container image — either the inline OCI reference (first branch) OR a data_reference to a governed container_image reference-data layer. The reference form lets DCM compute the change-impact blast radius when a base image or embedded library is bumped (UDLM ADR-012; DCM ADR-024) — an inline OCI string cannot be cascaded.
	Image string `json:"image"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`
	Network  *Network                     `json:"network,omitempty"`

	// Path Resource path or location within the system hierarchy.
	Path    *string  `json:"path,omitempty"`
	Process *Process `json:"process,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`
	Resources     *Resources                  `json:"resources,omitempty"`
	Runtime       *Runtime                    `json:"runtime,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime           *time.Time             `json:"update_time,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Env defines model for Env.
type Env struct {
	Name string `json:"name"`

	// Value Literal value — non-secret only.
	Value *string `json:"value,omitempty"`

	// ValueFrom Reference to a Security.CredentialRef or config source. Secret material is NEVER inline (DCM ADR-023).
	ValueFrom            *ValueFrom             `json:"value_from,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Mount defines model for Mount.
type Mount struct {
	MountPath string `json:"mount_path"`
	ReadOnly  *bool  `json:"read_only,omitempty"`

	// SourceRef handle/uuid of the mounted source (config/model snapshot
	SourceRef            string                 `json:"source_ref"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Network defines model for Network.
type Network struct {
	Ports                *[]Port                `json:"ports,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Port defines model for Port.
type Port struct {
	ContainerPort        int                    `json:"container_port"`
	Protocol             *PortProtocol          `json:"protocol,omitempty"`
	PublishedPort        *int                   `json:"published_port,omitempty"`
	Visibility           *PortVisibility        `json:"visibility,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PortProtocol defines model for Port.Protocol.
type PortProtocol string

// PortVisibility defines model for Port.Visibility.
type PortVisibility string

// Process defines model for Process.
type Process struct {
	Env                  *[]Env                 `json:"env,omitempty"`
	Mounts               *[]Mount               `json:"mounts,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Resources defines model for Resources.
type Resources struct {
	// Cpu vCPU request in cores.
	Cpu *float32 `json:"cpu,omitempty"`

	// InstanceSize Provider-neutral size class (small|medium|large) — size by class in place of cpu/memory; the provider maps it at naturalization (common-elements §2.2, ADR-014).
	InstanceSize         *string                `json:"instance_size,omitempty"`
	Memory               *string                `json:"memory,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	Replicas             *int                   `json:"replicas,omitempty"`
	RestartPolicy        *RuntimeRestartPolicy  `json:"restart_policy,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RuntimeRestartPolicy defines model for Runtime.RestartPolicy.
type RuntimeRestartPolicy string

// ValueFrom Reference to a Security.CredentialRef or config source. Secret material is NEVER inline (DCM ADR-023).
type ValueFrom struct {
	// CredentialRef handle or uuid of a Security.CredentialRef
	CredentialRef        *string                `json:"credential_ref,omitempty"`
	Key                  *string                `json:"key,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for ContainerSpec. Returns the specified
// element and whether it was found
func (a ContainerSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerSpec
func (a *ContainerSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerSpec to handle AdditionalProperties
func (a *ContainerSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["args"]; found {
		err = json.Unmarshal(raw, &a.Args)
		if err != nil {
			return fmt.Errorf("error reading 'args': %w", err)
		}
		delete(object, "args")
	}

	if raw, found := object["command"]; found {
		err = json.Unmarshal(raw, &a.Command)
		if err != nil {
			return fmt.Errorf("error reading 'command': %w", err)
		}
		delete(object, "command")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["image"]; found {
		err = json.Unmarshal(raw, &a.Image)
		if err != nil {
			return fmt.Errorf("error reading 'image': %w", err)
		}
		delete(object, "image")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["network"]; found {
		err = json.Unmarshal(raw, &a.Network)
		if err != nil {
			return fmt.Errorf("error reading 'network': %w", err)
		}
		delete(object, "network")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["process"]; found {
		err = json.Unmarshal(raw, &a.Process)
		if err != nil {
			return fmt.Errorf("error reading 'process': %w", err)
		}
		delete(object, "process")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["resources"]; found {
		err = json.Unmarshal(raw, &a.Resources)
		if err != nil {
			return fmt.Errorf("error reading 'resources': %w", err)
		}
		delete(object, "resources")
	}

	if raw, found := object["runtime"]; found {
		err = json.Unmarshal(raw, &a.Runtime)
		if err != nil {
			return fmt.Errorf("error reading 'runtime': %w", err)
		}
		delete(object, "runtime")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerSpec to handle AdditionalProperties
func (a ContainerSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Args != nil {
		object["args"], err = json.Marshal(a.Args)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'args': %w", err)
		}
	}

	if a.Command != nil {
		object["command"], err = json.Marshal(a.Command)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'command': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	object["image"], err = json.Marshal(a.Image)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'image': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Network != nil {
		object["network"], err = json.Marshal(a.Network)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'network': %w", err)
		}
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.Process != nil {
		object["process"], err = json.Marshal(a.Process)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'process': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	if a.Resources != nil {
		object["resources"], err = json.Marshal(a.Resources)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resources': %w", err)
		}
	}

	if a.Runtime != nil {
		object["runtime"], err = json.Marshal(a.Runtime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'runtime': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Env. Returns the specified
// element and whether it was found
func (a Env) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Env
func (a *Env) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Env to handle AdditionalProperties
func (a *Env) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if raw, found := object["value_from"]; found {
		err = json.Unmarshal(raw, &a.ValueFrom)
		if err != nil {
			return fmt.Errorf("error reading 'value_from': %w", err)
		}
		delete(object, "value_from")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Env to handle AdditionalProperties
func (a Env) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Value != nil {
		object["value"], err = json.Marshal(a.Value)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'value': %w", err)
		}
	}

	if a.ValueFrom != nil {
		object["value_from"], err = json.Marshal(a.ValueFrom)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'value_from': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Mount. Returns the specified
// element and whether it was found
func (a Mount) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Mount
func (a *Mount) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Mount to handle AdditionalProperties
func (a *Mount) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["mount_path"]; found {
		err = json.Unmarshal(raw, &a.MountPath)
		if err != nil {
			return fmt.Errorf("error reading 'mount_path': %w", err)
		}
		delete(object, "mount_path")
	}

	if raw, found := object["read_only"]; found {
		err = json.Unmarshal(raw, &a.ReadOnly)
		if err != nil {
			return fmt.Errorf("error reading 'read_only': %w", err)
		}
		delete(object, "read_only")
	}

	if raw, found := object["source_ref"]; found {
		err = json.Unmarshal(raw, &a.SourceRef)
		if err != nil {
			return fmt.Errorf("error reading 'source_ref': %w", err)
		}
		delete(object, "source_ref")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Mount to handle AdditionalProperties
func (a Mount) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["mount_path"], err = json.Marshal(a.MountPath)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mount_path': %w", err)
	}

	if a.ReadOnly != nil {
		object["read_only"], err = json.Marshal(a.ReadOnly)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'read_only': %w", err)
		}
	}

	object["source_ref"], err = json.Marshal(a.SourceRef)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source_ref': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Network. Returns the specified
// element and whether it was found
func (a Network) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Network
func (a *Network) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a *Network) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ports"]; found {
		err = json.Unmarshal(raw, &a.Ports)
		if err != nil {
			return fmt.Errorf("error reading 'ports': %w", err)
		}
		delete(object, "ports")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a Network) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Ports != nil {
		object["ports"], err = json.Marshal(a.Ports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ports': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Port. Returns the specified
// element and whether it was found
func (a Port) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Port
func (a *Port) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Port to handle AdditionalProperties
func (a *Port) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["container_port"]; found {
		err = json.Unmarshal(raw, &a.ContainerPort)
		if err != nil {
			return fmt.Errorf("error reading 'container_port': %w", err)
		}
		delete(object, "container_port")
	}

	if raw, found := object["protocol"]; found {
		err = json.Unmarshal(raw, &a.Protocol)
		if err != nil {
			return fmt.Errorf("error reading 'protocol': %w", err)
		}
		delete(object, "protocol")
	}

	if raw, found := object["published_port"]; found {
		err = json.Unmarshal(raw, &a.PublishedPort)
		if err != nil {
			return fmt.Errorf("error reading 'published_port': %w", err)
		}
		delete(object, "published_port")
	}

	if raw, found := object["visibility"]; found {
		err = json.Unmarshal(raw, &a.Visibility)
		if err != nil {
			return fmt.Errorf("error reading 'visibility': %w", err)
		}
		delete(object, "visibility")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Port to handle AdditionalProperties
func (a Port) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["container_port"], err = json.Marshal(a.ContainerPort)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'container_port': %w", err)
	}

	if a.Protocol != nil {
		object["protocol"], err = json.Marshal(a.Protocol)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'protocol': %w", err)
		}
	}

	if a.PublishedPort != nil {
		object["published_port"], err = json.Marshal(a.PublishedPort)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'published_port': %w", err)
		}
	}

	if a.Visibility != nil {
		object["visibility"], err = json.Marshal(a.Visibility)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'visibility': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Process. Returns the specified
// element and whether it was found
func (a Process) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Process
func (a *Process) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Process to handle AdditionalProperties
func (a *Process) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["env"]; found {
		err = json.Unmarshal(raw, &a.Env)
		if err != nil {
			return fmt.Errorf("error reading 'env': %w", err)
		}
		delete(object, "env")
	}

	if raw, found := object["mounts"]; found {
		err = json.Unmarshal(raw, &a.Mounts)
		if err != nil {
			return fmt.Errorf("error reading 'mounts': %w", err)
		}
		delete(object, "mounts")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Process to handle AdditionalProperties
func (a Process) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Env != nil {
		object["env"], err = json.Marshal(a.Env)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'env': %w", err)
		}
	}

	if a.Mounts != nil {
		object["mounts"], err = json.Marshal(a.Mounts)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mounts': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Resources. Returns the specified
// element and whether it was found
func (a Resources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Resources
func (a *Resources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Resources to handle AdditionalProperties
func (a *Resources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["instance_size"]; found {
		err = json.Unmarshal(raw, &a.InstanceSize)
		if err != nil {
			return fmt.Errorf("error reading 'instance_size': %w", err)
		}
		delete(object, "instance_size")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Resources to handle AdditionalProperties
func (a Resources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Cpu != nil {
		object["cpu"], err = json.Marshal(a.Cpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
		}
	}

	if a.InstanceSize != nil {
		object["instance_size"], err = json.Marshal(a.InstanceSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_size': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Runtime. Returns the specified
// element and whether it was found
func (a Runtime) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Runtime
func (a *Runtime) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Runtime to handle AdditionalProperties
func (a *Runtime) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["replicas"]; found {
		err = json.Unmarshal(raw, &a.Replicas)
		if err != nil {
			return fmt.Errorf("error reading 'replicas': %w", err)
		}
		delete(object, "replicas")
	}

	if raw, found := object["restart_policy"]; found {
		err = json.Unmarshal(raw, &a.RestartPolicy)
		if err != nil {
			return fmt.Errorf("error reading 'restart_policy': %w", err)
		}
		delete(object, "restart_policy")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Runtime to handle AdditionalProperties
func (a Runtime) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Replicas != nil {
		object["replicas"], err = json.Marshal(a.Replicas)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'replicas': %w", err)
		}
	}

	if a.RestartPolicy != nil {
		object["restart_policy"], err = json.Marshal(a.RestartPolicy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'restart_policy': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ValueFrom. Returns the specified
// element and whether it was found
func (a ValueFrom) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ValueFrom
func (a *ValueFrom) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ValueFrom to handle AdditionalProperties
func (a *ValueFrom) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["credential_ref"]; found {
		err = json.Unmarshal(raw, &a.CredentialRef)
		if err != nil {
			return fmt.Errorf("error reading 'credential_ref': %w", err)
		}
		delete(object, "credential_ref")
	}

	if raw, found := object["key"]; found {
		err = json.Unmarshal(raw, &a.Key)
		if err != nil {
			return fmt.Errorf("error reading 'key': %w", err)
		}
		delete(object, "key")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ValueFrom to handle AdditionalProperties
func (a ValueFrom) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CredentialRef != nil {
		object["credential_ref"], err = json.Marshal(a.CredentialRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'credential_ref': %w", err)
		}
	}

	if a.Key != nil {
		object["key"], err = json.Marshal(a.Key)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'key': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
