// Package udlm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package udlm

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fhtbxs3Ev4rBK9AE9xqV059aKr7FCROkUOcBk7d+2D5FGo50rLlkhtyKFk19N8PJPdVWsUxkAaH+7Zv",
	"nBnOPM/Dmb2nuS4rrUChpbN7WjHDSkAw4e5CocDdtRP8PcPCP+FgcyMqFFrRGf21AALhm+8tcU5w8mRz",
	"/jQhtmAGOFnuCJOS6BURaImBXBtuaUKFX1t5iwlVrAQ6o9B6ogk18MkJA5zO0DhIqM0LKFkMDxGMX/6f",
	"m+nkJzZZ3d4/30/a6/P95Ly9+WE/uXn+E1veDp4012fP9t/RhOKu8v4tGqHWdL/fe/e20spCSMErWDEn",
	"8cIYbfx9rhWCQn/JqkqKnPlcZJXRSwnl33+3PjH3vZC/M7CiM/q3rEt0Ft/aLFoNToeJvVZwV0GOwAnE",
	"bxL6TuNr7RT/dlG8003RyEobgoWwdbl9PNeKOSy0EX/CN4zphcPCxxCtkxYq/st6cYfcD64smdkdA/cX",
	"1QCXYMGQFMwShkQCs0i0AnL96u1lvXma0MroCgyKCIm4cOHx7m8PEJRQyRAsLhiOE+Yjw4+eE1gAUbAF",
	"i52jY1tiBfkul7CwyBAeoGDujAGFpNJWhPQIFdystDOTYICUmoOkCQXlSjq7oW9i0RJ6BZ8cWAQerpkM",
	"ZU3oK2FzvQGf4tuR+GLki1y7WPn6A6EQ1mDiF1Y7k8MivhqLPyQ7l8zahEC6TsklywuhIP3tciwnCIop",
	"PJ1//2CxAWNFRNwhxfsCczOo5tD2YewHlo+Lc5COLl96+Tvk6GMb4PKtsCFpI/CqrwVCaR/kygDr+9Yr",
	"M4aFewV3uKjYGhao/4AvzYkP4fQWfhOwDVTnPECNyfe9XUTdPq60j94FVYvk2wjYpsS/sQWrgAgb8Gpg",
	"LSya3fd2rprrLC6ZhCVx66nXlH9GXXrx/g3hGixR2vMpgl1gOleP5+8x574SW4I9+1DajjJ+ItKDotWY",
	"HeL5GKJ1DKOVbQ65YeGuXr8kPz6f/hiqJwVTGA8l0hyURxnmgEzI0eQKZZGpPGR1pU3pVZI6IyYGVmDA",
	"vzmROGfHBQYFSjgpBI/xc5DQhvTB/li+PvhUXkXtfhQVfmlOmAoaXY7KQeCO5Sh3hFliURvgX8qOYGUS",
	"rfy19Kg1rkluQw0RqLFojzLTMKT/KBKle8JbvjTPPnPInIzo69L0AAX97TauDlnWD/ABoIxrftMbf6nk",
	"95F3JPijGxhjvE8d5M7408MbjrEsgRkwvs/q7l43DPrXv3+ldaPlLcW3HZMKxCp2bUKtdNMVstxv+aiV",
	"e/XyMrLAg3NCDDBOWJ6DtQR1QPooRyIJvF2jJakkUzBXWyMQLFmCFRzCuKG3ihi9teRJRGZCWkT6y4iF",
	"pwlhijfuYlHnyh8x3VG1Mrr0r8tZ+Ch2dw1f9YoAywsSAkzISksOnAiF2reRc8V17krfkvmlW7brttWx",
	"uPa7CG5RaxnM2EjPubqqd80MEFGWDtlSQgjbP1GwAUP89hF8s2e0Wxct5yO/pcjBy/Tsvhm3XlQsL4A8",
	"S6c0oc7IunR2lmXb7TZl4XWqzTqr19rs7ZuXF+8+XEyepdO0wFL2pJc2VaQJbfsuujljsirYmf9QV6BY",
	"JeiM/pBO03OvOQyLALfMcVlm/aZnDSOd8xWgM8qG5tzGVscjo85dQrThUM+cdW/h2ZjS4NuEYeENpzPq",
	"+XfNZXnROEwGM+/Nod9LdidKVxLlyiUYX28D1km0wbtvqpqB9pMDs+sm2pLdxZ7Lij+B9odYHkdKOjub",
	"ThP/nXdAZ/8Id0LFu7Pk6KjbJ0fNs2/nwmxWsbVQYZcnwum1f/1YDrXv9mD8fTadfma2e+RMd9T7jsx3",
	"H1xQgJWTpC2cR9D59OyU/TbgbDCSBtN1ph9aOJjygy42k2MADGng2UyLm8GE6EGEbG1DF8ZlSW+9iSGw",
	"s/vuF8f+JMoHPXIQxDCvhRLrdmZ9UIjmyikOhnyMzd7HhIDagNQVkJUAry2NqJFSW5w0clgbq0WxgLnK",
	"mTHC00rq/A9LnsRGLCEcKlAcVC7AJqQEZJwhS0gAqwmMTNP0KUEWEGp0OVfeXRTyYRdzrH9+VZD5MiyN",
	"Kjbk8c/Q0Xh3TOKxcnefZAc/tr4B7MO89Ffj/Xx6/vCi9j/SVyLIz4C90zOMdI/lQ9brf0Z5cbGBqPfD",
	"bjn+lYLuEJDcU2IljMUk8qFrpD9/FOyuWir/70LpsI/8v8RTEFzs/9Y6rbK9DjbUqt+73tz6Wlgwm6aS",
	"sdHJWCWyrjm5ba0egq6v8EERewi33ckaYtnf7v8bAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
