// Package udlm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package udlm

import (
	"encoding/json"
	"fmt"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for EntitySummaryLifecycleState.
const (
	EntitySummaryLifecycleStateDiscovered EntitySummaryLifecycleState = "Discovered"
	EntitySummaryLifecycleStateIntent     EntitySummaryLifecycleState = "Intent"
	EntitySummaryLifecycleStateRealized   EntitySummaryLifecycleState = "Realized"
	EntitySummaryLifecycleStateRequested  EntitySummaryLifecycleState = "Requested"
)

// Valid indicates whether the value is a known member of the EntitySummaryLifecycleState enum.
func (e EntitySummaryLifecycleState) Valid() bool {
	switch e {
	case EntitySummaryLifecycleStateDiscovered:
		return true
	case EntitySummaryLifecycleStateIntent:
		return true
	case EntitySummaryLifecycleStateRealized:
		return true
	case EntitySummaryLifecycleStateRequested:
		return true
	default:
		return false
	}
}

// Defines values for EntityViewLifecycleState.
const (
	EntityViewLifecycleStateDiscovered EntityViewLifecycleState = "Discovered"
	EntityViewLifecycleStateIntent     EntityViewLifecycleState = "Intent"
	EntityViewLifecycleStateRealized   EntityViewLifecycleState = "Realized"
	EntityViewLifecycleStateRequested  EntityViewLifecycleState = "Requested"
)

// Valid indicates whether the value is a known member of the EntityViewLifecycleState enum.
func (e EntityViewLifecycleState) Valid() bool {
	switch e {
	case EntityViewLifecycleStateDiscovered:
		return true
	case EntityViewLifecycleStateIntent:
		return true
	case EntityViewLifecycleStateRealized:
		return true
	case EntityViewLifecycleStateRequested:
		return true
	default:
		return false
	}
}

// Defines values for StateRecordRecordType.
const (
	DiscoveredRecord StateRecordRecordType = "discovered_record"
	IntentRecord     StateRecordRecordType = "intent_record"
	RealizedRecord   StateRecordRecordType = "realized_record"
	RequestedRecord  StateRecordRecordType = "requested_record"
)

// Valid indicates whether the value is a known member of the StateRecordRecordType enum.
func (e StateRecordRecordType) Valid() bool {
	switch e {
	case DiscoveredRecord:
		return true
	case IntentRecord:
		return true
	case RealizedRecord:
		return true
	case RequestedRecord:
		return true
	default:
		return false
	}
}

// Defines values for StateRecordState.
const (
	Discovered StateRecordState = "Discovered"
	Intent     StateRecordState = "Intent"
	Realized   StateRecordState = "Realized"
	Requested  StateRecordState = "Requested"
)

// Valid indicates whether the value is a known member of the StateRecordState enum.
func (e StateRecordState) Valid() bool {
	switch e {
	case Discovered:
		return true
	case Intent:
		return true
	case Realized:
		return true
	case Requested:
		return true
	default:
		return false
	}
}

// EntitySummary One entity that has at least one UDLM record
type EntitySummary struct {
	EntityUuid string `json:"entity_uuid"`

	// LatestAt The `at` of the newest record
	LatestAt *string `json:"latest_at,omitempty"`

	// LifecycleState The entity's current position in the four-state model
	LifecycleState EntitySummaryLifecycleState `json:"lifecycle_state"`
	RecordCount    int                         `json:"record_count"`

	// ResourceType The UDLM class, e.g. Machine.VM
	ResourceType string `json:"resource_type"`
	TenantUuid   string `json:"tenant_uuid"`
	TypeVersion  string `json:"type_version"`
}

// EntitySummaryLifecycleState The entity's current position in the four-state model
type EntitySummaryLifecycleState string

// EntitySummaryList defines model for EntitySummaryList.
type EntitySummaryList struct {
	Entities      []EntitySummary `json:"entities"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// EntityView The computed entity view. The shape is the registry's
// registry/entity-view.schema.json; this API does not restate it.
type EntityView struct {
	EntityUuid           string                   `json:"entity_uuid"`
	LifecycleState       EntityViewLifecycleState `json:"lifecycle_state"`
	States               map[string]interface{}   `json:"states"`
	Uuid                 string                   `json:"uuid"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// EntityViewLifecycleState defines model for EntityView.LifecycleState.
type EntityViewLifecycleState string

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// StateRecord One UDLM per-state record exactly as stored. The shape is the registry's
// registry/state-record.schema.json; this API does not restate it.
type StateRecord struct {
	EntityUuid           string                 `json:"entity_uuid"`
	RecordType           StateRecordRecordType  `json:"record_type"`
	RecordUuid           string                 `json:"record_uuid"`
	State                StateRecordState       `json:"state"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StateRecordRecordType defines model for StateRecord.RecordType.
type StateRecordRecordType string

// StateRecordState defines model for StateRecord.State.
type StateRecordState string

// StateRecordList defines model for StateRecordList.
type StateRecordList struct {
	Records []StateRecord `json:"records"`
}

// EntityUuidPath defines model for EntityUuidPath.
type EntityUuidPath = string

// DefaultError RFC 7807 compliant error response
type DefaultError = Error

// NotFound RFC 7807 compliant error response
type NotFound = Error

// Unauthorized RFC 7807 compliant error response
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListUdlmEntitiesParams defines parameters for ListUdlmEntities.
type ListUdlmEntitiesParams struct {
	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// Getter for additional properties for EntityView. Returns the specified
// element and whether it was found
func (a EntityView) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EntityView
func (a *EntityView) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EntityView to handle AdditionalProperties
func (a *EntityView) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entity_uuid"]; found {
		err = json.Unmarshal(raw, &a.EntityUuid)
		if err != nil {
			return fmt.Errorf("error reading 'entity_uuid': %w", err)
		}
		delete(object, "entity_uuid")
	}

	if raw, found := object["lifecycle_state"]; found {
		err = json.Unmarshal(raw, &a.LifecycleState)
		if err != nil {
			return fmt.Errorf("error reading 'lifecycle_state': %w", err)
		}
		delete(object, "lifecycle_state")
	}

	if raw, found := object["states"]; found {
		err = json.Unmarshal(raw, &a.States)
		if err != nil {
			return fmt.Errorf("error reading 'states': %w", err)
		}
		delete(object, "states")
	}

	if raw, found := object["uuid"]; found {
		err = json.Unmarshal(raw, &a.Uuid)
		if err != nil {
			return fmt.Errorf("error reading 'uuid': %w", err)
		}
		delete(object, "uuid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EntityView to handle AdditionalProperties
func (a EntityView) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["entity_uuid"], err = json.Marshal(a.EntityUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'entity_uuid': %w", err)
	}

	object["lifecycle_state"], err = json.Marshal(a.LifecycleState)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'lifecycle_state': %w", err)
	}

	if a.States != nil {
		object["states"], err = json.Marshal(a.States)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'states': %w", err)
		}
	}

	object["uuid"], err = json.Marshal(a.Uuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'uuid': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for StateRecord. Returns the specified
// element and whether it was found
func (a StateRecord) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StateRecord
func (a *StateRecord) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StateRecord to handle AdditionalProperties
func (a *StateRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entity_uuid"]; found {
		err = json.Unmarshal(raw, &a.EntityUuid)
		if err != nil {
			return fmt.Errorf("error reading 'entity_uuid': %w", err)
		}
		delete(object, "entity_uuid")
	}

	if raw, found := object["record_type"]; found {
		err = json.Unmarshal(raw, &a.RecordType)
		if err != nil {
			return fmt.Errorf("error reading 'record_type': %w", err)
		}
		delete(object, "record_type")
	}

	if raw, found := object["record_uuid"]; found {
		err = json.Unmarshal(raw, &a.RecordUuid)
		if err != nil {
			return fmt.Errorf("error reading 'record_uuid': %w", err)
		}
		delete(object, "record_uuid")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StateRecord to handle AdditionalProperties
func (a StateRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["entity_uuid"], err = json.Marshal(a.EntityUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'entity_uuid': %w", err)
	}

	object["record_type"], err = json.Marshal(a.RecordType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'record_type': %w", err)
	}

	object["record_uuid"], err = json.Marshal(a.RecordUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'record_uuid': %w", err)
	}

	object["state"], err = json.Marshal(a.State)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'state': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
