// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for EntitySummaryLifecycleState.
const (
	EntitySummaryLifecycleStateDiscovered EntitySummaryLifecycleState = "Discovered"
	EntitySummaryLifecycleStateIntent     EntitySummaryLifecycleState = "Intent"
	EntitySummaryLifecycleStateRealized   EntitySummaryLifecycleState = "Realized"
	EntitySummaryLifecycleStateRequested  EntitySummaryLifecycleState = "Requested"
)

// Valid indicates whether the value is a known member of the EntitySummaryLifecycleState enum.
func (e EntitySummaryLifecycleState) Valid() bool {
	switch e {
	case EntitySummaryLifecycleStateDiscovered:
		return true
	case EntitySummaryLifecycleStateIntent:
		return true
	case EntitySummaryLifecycleStateRealized:
		return true
	case EntitySummaryLifecycleStateRequested:
		return true
	default:
		return false
	}
}

// Defines values for EntityViewLifecycleState.
const (
	EntityViewLifecycleStateDiscovered EntityViewLifecycleState = "Discovered"
	EntityViewLifecycleStateIntent     EntityViewLifecycleState = "Intent"
	EntityViewLifecycleStateRealized   EntityViewLifecycleState = "Realized"
	EntityViewLifecycleStateRequested  EntityViewLifecycleState = "Requested"
)

// Valid indicates whether the value is a known member of the EntityViewLifecycleState enum.
func (e EntityViewLifecycleState) Valid() bool {
	switch e {
	case EntityViewLifecycleStateDiscovered:
		return true
	case EntityViewLifecycleStateIntent:
		return true
	case EntityViewLifecycleStateRealized:
		return true
	case EntityViewLifecycleStateRequested:
		return true
	default:
		return false
	}
}

// Defines values for StateRecordRecordType.
const (
	DiscoveredRecord StateRecordRecordType = "discovered_record"
	IntentRecord     StateRecordRecordType = "intent_record"
	RealizedRecord   StateRecordRecordType = "realized_record"
	RequestedRecord  StateRecordRecordType = "requested_record"
)

// Valid indicates whether the value is a known member of the StateRecordRecordType enum.
func (e StateRecordRecordType) Valid() bool {
	switch e {
	case DiscoveredRecord:
		return true
	case IntentRecord:
		return true
	case RealizedRecord:
		return true
	case RequestedRecord:
		return true
	default:
		return false
	}
}

// Defines values for StateRecordState.
const (
	Discovered StateRecordState = "Discovered"
	Intent     StateRecordState = "Intent"
	Realized   StateRecordState = "Realized"
	Requested  StateRecordState = "Requested"
)

// Valid indicates whether the value is a known member of the StateRecordState enum.
func (e StateRecordState) Valid() bool {
	switch e {
	case Discovered:
		return true
	case Intent:
		return true
	case Realized:
		return true
	case Requested:
		return true
	default:
		return false
	}
}

// EntitySummary One entity that has at least one UDLM record
type EntitySummary struct {
	EntityUuid string `json:"entity_uuid"`

	// LatestAt The `at` of the newest record
	LatestAt *string `json:"latest_at,omitempty"`

	// LifecycleState The entity's current position in the four-state model
	LifecycleState EntitySummaryLifecycleState `json:"lifecycle_state"`
	RecordCount    int                         `json:"record_count"`

	// ResourceType The UDLM class, e.g. Machine.VM
	ResourceType string `json:"resource_type"`
	TenantUuid   string `json:"tenant_uuid"`
	TypeVersion  string `json:"type_version"`
}

// EntitySummaryLifecycleState The entity's current position in the four-state model
type EntitySummaryLifecycleState string

// EntitySummaryList defines model for EntitySummaryList.
type EntitySummaryList struct {
	Entities      []EntitySummary `json:"entities"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// EntityView The computed entity view. The shape is the registry's
// registry/entity-view.schema.json; this API does not restate it.
type EntityView struct {
	EntityUuid           string                   `json:"entity_uuid"`
	LifecycleState       EntityViewLifecycleState `json:"lifecycle_state"`
	States               map[string]interface{}   `json:"states"`
	Uuid                 string                   `json:"uuid"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// EntityViewLifecycleState defines model for EntityView.LifecycleState.
type EntityViewLifecycleState string

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// StateRecord One UDLM per-state record exactly as stored. The shape is the registry's
// registry/state-record.schema.json; this API does not restate it.
type StateRecord struct {
	EntityUuid           string                 `json:"entity_uuid"`
	RecordType           StateRecordRecordType  `json:"record_type"`
	RecordUuid           string                 `json:"record_uuid"`
	State                StateRecordState       `json:"state"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StateRecordRecordType defines model for StateRecord.RecordType.
type StateRecordRecordType string

// StateRecordState defines model for StateRecord.State.
type StateRecordState string

// StateRecordList defines model for StateRecordList.
type StateRecordList struct {
	Records []StateRecord `json:"records"`
}

// EntityUuidPath defines model for EntityUuidPath.
type EntityUuidPath = string

// DefaultError RFC 7807 compliant error response
type DefaultError = Error

// NotFound RFC 7807 compliant error response
type NotFound = Error

// Unauthorized RFC 7807 compliant error response
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListUdlmEntitiesParams defines parameters for ListUdlmEntities.
type ListUdlmEntitiesParams struct {
	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// Getter for additional properties for EntityView. Returns the specified
// element and whether it was found
func (a EntityView) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EntityView
func (a *EntityView) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EntityView to handle AdditionalProperties
func (a *EntityView) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entity_uuid"]; found {
		err = json.Unmarshal(raw, &a.EntityUuid)
		if err != nil {
			return fmt.Errorf("error reading 'entity_uuid': %w", err)
		}
		delete(object, "entity_uuid")
	}

	if raw, found := object["lifecycle_state"]; found {
		err = json.Unmarshal(raw, &a.LifecycleState)
		if err != nil {
			return fmt.Errorf("error reading 'lifecycle_state': %w", err)
		}
		delete(object, "lifecycle_state")
	}

	if raw, found := object["states"]; found {
		err = json.Unmarshal(raw, &a.States)
		if err != nil {
			return fmt.Errorf("error reading 'states': %w", err)
		}
		delete(object, "states")
	}

	if raw, found := object["uuid"]; found {
		err = json.Unmarshal(raw, &a.Uuid)
		if err != nil {
			return fmt.Errorf("error reading 'uuid': %w", err)
		}
		delete(object, "uuid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EntityView to handle AdditionalProperties
func (a EntityView) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["entity_uuid"], err = json.Marshal(a.EntityUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'entity_uuid': %w", err)
	}

	object["lifecycle_state"], err = json.Marshal(a.LifecycleState)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'lifecycle_state': %w", err)
	}

	if a.States != nil {
		object["states"], err = json.Marshal(a.States)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'states': %w", err)
		}
	}

	object["uuid"], err = json.Marshal(a.Uuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'uuid': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for StateRecord. Returns the specified
// element and whether it was found
func (a StateRecord) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StateRecord
func (a *StateRecord) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StateRecord to handle AdditionalProperties
func (a *StateRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["entity_uuid"]; found {
		err = json.Unmarshal(raw, &a.EntityUuid)
		if err != nil {
			return fmt.Errorf("error reading 'entity_uuid': %w", err)
		}
		delete(object, "entity_uuid")
	}

	if raw, found := object["record_type"]; found {
		err = json.Unmarshal(raw, &a.RecordType)
		if err != nil {
			return fmt.Errorf("error reading 'record_type': %w", err)
		}
		delete(object, "record_type")
	}

	if raw, found := object["record_uuid"]; found {
		err = json.Unmarshal(raw, &a.RecordUuid)
		if err != nil {
			return fmt.Errorf("error reading 'record_uuid': %w", err)
		}
		delete(object, "record_uuid")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StateRecord to handle AdditionalProperties
func (a StateRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["entity_uuid"], err = json.Marshal(a.EntityUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'entity_uuid': %w", err)
	}

	object["record_type"], err = json.Marshal(a.RecordType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'record_type': %w", err)
	}

	object["record_uuid"], err = json.Marshal(a.RecordUuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'record_uuid': %w", err)
	}

	object["state"], err = json.Marshal(a.State)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'state': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List entities that have UDLM records
	// (GET /udlm/entities)
	ListUdlmEntities(w http.ResponseWriter, r *http.Request, params ListUdlmEntitiesParams)
	// Get the entity view
	// (GET /udlm/entities/{entityUuid})
	GetUdlmEntity(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath)
	// List the entity's records
	// (GET /udlm/entities/{entityUuid}/records)
	ListUdlmEntityRecords(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List entities that have UDLM records
// (GET /udlm/entities)
func (_ Unimplemented) ListUdlmEntities(w http.ResponseWriter, r *http.Request, params ListUdlmEntitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the entity view
// (GET /udlm/entities/{entityUuid})
func (_ Unimplemented) GetUdlmEntity(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the entity's records
// (GET /udlm/entities/{entityUuid}/records)
func (_ Unimplemented) ListUdlmEntityRecords(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUdlmEntities operation middleware
func (siw *ServerInterfaceWrapper) ListUdlmEntities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUdlmEntitiesParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUdlmEntities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUdlmEntity operation middleware
func (siw *ServerInterfaceWrapper) GetUdlmEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityUuid" -------------
	var entityUuid EntityUuidPath

	err = runtime.BindStyledParameterWithOptions("simple", "entityUuid", chi.URLParam(r, "entityUuid"), &entityUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityUuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUdlmEntity(w, r, entityUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUdlmEntityRecords operation middleware
func (siw *ServerInterfaceWrapper) ListUdlmEntityRecords(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityUuid" -------------
	var entityUuid EntityUuidPath

	err = runtime.BindStyledParameterWithOptions("simple", "entityUuid", chi.URLParam(r, "entityUuid"), &entityUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityUuid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUdlmEntityRecords(w, r, entityUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/udlm/entities", wrapper.ListUdlmEntities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/udlm/entities/{entityUuid}", wrapper.GetUdlmEntity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/udlm/entities/{entityUuid}/records", wrapper.ListUdlmEntityRecords)
	})

	return r
}

type DefaultErrorApplicationProblemPlusJSONResponse Error

type NotFoundApplicationProblemPlusJSONResponse Error

type UnauthorizedApplicationProblemPlusJSONResponse Error

type ListUdlmEntitiesRequestObject struct {
	Params ListUdlmEntitiesParams
}

type ListUdlmEntitiesResponseObject interface {
	VisitListUdlmEntitiesResponse(w http.ResponseWriter) error
}

type ListUdlmEntities200JSONResponse EntitySummaryList

func (response ListUdlmEntities200JSONResponse) VisitListUdlmEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntities401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListUdlmEntities401ApplicationProblemPlusJSONResponse) VisitListUdlmEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntitiesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListUdlmEntitiesdefaultApplicationProblemPlusJSONResponse) VisitListUdlmEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetUdlmEntityRequestObject struct {
	EntityUuid EntityUuidPath `json:"entityUuid"`
}

type GetUdlmEntityResponseObject interface {
	VisitGetUdlmEntityResponse(w http.ResponseWriter) error
}

type GetUdlmEntity200JSONResponse EntityView

func (response GetUdlmEntity200JSONResponse) VisitGetUdlmEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUdlmEntity401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetUdlmEntity401ApplicationProblemPlusJSONResponse) VisitGetUdlmEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUdlmEntity404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetUdlmEntity404ApplicationProblemPlusJSONResponse) VisitGetUdlmEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUdlmEntitydefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetUdlmEntitydefaultApplicationProblemPlusJSONResponse) VisitGetUdlmEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntityRecordsRequestObject struct {
	EntityUuid EntityUuidPath `json:"entityUuid"`
}

type ListUdlmEntityRecordsResponseObject interface {
	VisitListUdlmEntityRecordsResponse(w http.ResponseWriter) error
}

type ListUdlmEntityRecords200JSONResponse StateRecordList

func (response ListUdlmEntityRecords200JSONResponse) VisitListUdlmEntityRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntityRecords401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListUdlmEntityRecords401ApplicationProblemPlusJSONResponse) VisitListUdlmEntityRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntityRecords404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListUdlmEntityRecords404ApplicationProblemPlusJSONResponse) VisitListUdlmEntityRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListUdlmEntityRecordsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListUdlmEntityRecordsdefaultApplicationProblemPlusJSONResponse) VisitListUdlmEntityRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List entities that have UDLM records
	// (GET /udlm/entities)
	ListUdlmEntities(ctx context.Context, request ListUdlmEntitiesRequestObject) (ListUdlmEntitiesResponseObject, error)
	// Get the entity view
	// (GET /udlm/entities/{entityUuid})
	GetUdlmEntity(ctx context.Context, request GetUdlmEntityRequestObject) (GetUdlmEntityResponseObject, error)
	// List the entity's records
	// (GET /udlm/entities/{entityUuid}/records)
	ListUdlmEntityRecords(ctx context.Context, request ListUdlmEntityRecordsRequestObject) (ListUdlmEntityRecordsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListUdlmEntities operation middleware
func (sh *strictHandler) ListUdlmEntities(w http.ResponseWriter, r *http.Request, params ListUdlmEntitiesParams) {
	var request ListUdlmEntitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUdlmEntities(ctx, request.(ListUdlmEntitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUdlmEntities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUdlmEntitiesResponseObject); ok {
		if err := validResponse.VisitListUdlmEntitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUdlmEntity operation middleware
func (sh *strictHandler) GetUdlmEntity(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath) {
	var request GetUdlmEntityRequestObject

	request.EntityUuid = entityUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUdlmEntity(ctx, request.(GetUdlmEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUdlmEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUdlmEntityResponseObject); ok {
		if err := validResponse.VisitGetUdlmEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUdlmEntityRecords operation middleware
func (sh *strictHandler) ListUdlmEntityRecords(w http.ResponseWriter, r *http.Request, entityUuid EntityUuidPath) {
	var request ListUdlmEntityRecordsRequestObject

	request.EntityUuid = entityUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUdlmEntityRecords(ctx, request.(ListUdlmEntityRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUdlmEntityRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUdlmEntityRecordsResponseObject); ok {
		if err := validResponse.VisitListUdlmEntityRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
