// Package database provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package database

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// Defines values for DatabaseSpecEngine.
const (
	Mysql    DatabaseSpecEngine = "mysql"
	Postgres DatabaseSpecEngine = "postgres"
)

// Valid indicates whether the value is a known member of the DatabaseSpecEngine enum.
func (e DatabaseSpecEngine) Valid() bool {
	switch e {
	case Mysql:
		return true
	case Postgres:
		return true
	default:
		return false
	}
}

// DatabaseSpec defines model for DatabaseSpec.
type DatabaseSpec struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Engine Database engine.
	Engine DatabaseSpecEngine `json:"engine"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`
	Resources     Resources                   `json:"resources"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version Engine version. Concrete (e.g. `16`, engine-dependent — see registry conditional-constraints, E3) OR an abstract channel the PROVIDER resolves (`latest`, `lts`). Optional: when omitted it defaults to `latest`. Because the value may be abstract, two provider obligations apply (ADR-014; provider-contract §8.1a): (1) the provider DECLARES its channel→version resolution so an abstract request stays comparable/conformable/validatable against a pinned requirement and across compatible providers (declared, not live-queried); (2) the concrete version actually provisioned is recorded in outputs.applied_version for audit. Intent carries the abstract; realized carries the concrete.
	Version              *string                `json:"version,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DatabaseSpecEngine Database engine.
type DatabaseSpecEngine string

// Resources defines model for Resources.
type Resources struct {
	// Cpu CPU allocation, as a millicore string (`500m`) or whole/fractional cores (`2`, `1.5`) — Kubernetes-aligned quantity convention (Noam, #40). The provider reconciles to its concrete units at naturalization.
	Cpu *string `json:"cpu,omitempty"`

	// InstanceSize Provider-neutral size class (e.g. small|medium|large, or a named profile). Generic sizing INTENT — usable in place of, or alongside, explicit cpu/memory/storage. The PROVIDER reconciles it to concrete resources / its own instance classes at naturalization (DCM ADR-023, provider-naturalization boundary); UDLM/DCM does NOT define the mapping. A shared sizing option available to any resource type (common-elements §sizing).
	InstanceSize         *string                `json:"instance_size,omitempty"`
	Memory               *string                `json:"memory,omitempty"`
	Storage              *string                `json:"storage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for DatabaseSpec. Returns the specified
// element and whether it was found
func (a DatabaseSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseSpec
func (a *DatabaseSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseSpec to handle AdditionalProperties
func (a *DatabaseSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["engine"]; found {
		err = json.Unmarshal(raw, &a.Engine)
		if err != nil {
			return fmt.Errorf("error reading 'engine': %w", err)
		}
		delete(object, "engine")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["resources"]; found {
		err = json.Unmarshal(raw, &a.Resources)
		if err != nil {
			return fmt.Errorf("error reading 'resources': %w", err)
		}
		delete(object, "resources")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseSpec to handle AdditionalProperties
func (a DatabaseSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	object["engine"], err = json.Marshal(a.Engine)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'engine': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["resources"], err = json.Marshal(a.Resources)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resources': %w", err)
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	if a.Version != nil {
		object["version"], err = json.Marshal(a.Version)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'version': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Resources. Returns the specified
// element and whether it was found
func (a Resources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Resources
func (a *Resources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Resources to handle AdditionalProperties
func (a *Resources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["instance_size"]; found {
		err = json.Unmarshal(raw, &a.InstanceSize)
		if err != nil {
			return fmt.Errorf("error reading 'instance_size': %w", err)
		}
		delete(object, "instance_size")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Resources to handle AdditionalProperties
func (a Resources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Cpu != nil {
		object["cpu"], err = json.Marshal(a.Cpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
		}
	}

	if a.InstanceSize != nil {
		object["instance_size"], err = json.Marshal(a.InstanceSize)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_size': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
