name: CI

on:
  push:
    branches: [main, udlm-native, 'release/v*']
  pull_request:
    branches: [main, udlm-native, 'release/v*']

jobs:
  ci:
    uses: dcm-project/shared-workflows/.github/workflows/go-ci.yaml@main
