name: Lint

on:
  push:
    branches: [main, udlm-native, 'release/v*']
  pull_request:
    branches: [main, udlm-native, 'release/v*']

jobs:
  lint:
    uses: dcm-project/shared-workflows/.github/workflows/go-lint.yaml@main
